### ISSUE TITLE
Geoserver cleanup

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#101]
The layers on Geoserver are stored in groups named scratchTJS and TravisTest. This should be set to a more professional looking name. 

Please propose a naming scheme. Note that this will break our UI. I suggest to

1. create copies of the files to the new naming convention (Travis, Trevor)
2. modify the links in the UI to the new names (Long, hope you're OK with React.js)
3. deploy on medus to check everything works (Mourad, Long, are you able to run the https://github.com/Ouranosinc/PAVICS-e2e-ui-tests ?)
4. deploy on boreas (Mourad)

**Comment by tlogan2000** [comment]
FOr the store : 'PAVICS_frontend' or 'PAVICS_regions' ?  Any objections / suggestions?

**Comment by huard** [comment]
Question: Do you plan to use the same geoserver instance for non-pavics stuff ? 

Also, I'm guessing we might want to use the same shapes for the frontend and services, so the distinction between frontend and regions might cause confusion.

**Comment by Zeitsperre** [comment]
I would be fine with either of those or `PAVICS_public`? If PAVICS will eventually be running on multiple servers, it would be good to use generic names that can be copied over without issue (versus `Ouranos_public `or `<servername>_public`).

**Comment by huard** [comment]
Good point. And since DACCS is going to be the next gen PAVICS, we might want to avoid putting the name PAVICS everywhere. 
Just "public" ? Or the name of the provider (public might get crowded too fast) ?

**Comment by tlogan2000** [comment]
I was thinking one or the other for the names (not both).   
For non-pavics things could a separate store  contain 'non-pavics' data and layers? or does the front-end see everything on the geoserver instance?

**Comment by tlogan2000** [comment]
Maybe this (assuming we can get the front-end to point to a single store)

Ouranos_frontend : data for region picker (polygons etc) and subsetting of the frontend
Ouranos_public : Other WMS, WCS data layers, potentially realted or non-related to pavics.  E.g. Synthese 2015 data (temp, precip) or finch calculated indices we want to expose as web services?

**Comment by huard** [comment]
I think the naming should not reflect the usage (frontend), as it's likely to be used in more than one way. What about the source?

**Comment by tlvu** [comment]
>     2. modify the links in the UI to the new names (Long, hope you're OK with React.js)

Never used React.js, but if just to change the links to the new name, should be simple I guess.

>     3. deploy on medus to check everything works (Mourad, Long, are you able to run the https://github.com/Ouranosinc/PAVICS-e2e-ui-tests ?)

Not tried to run [PAVICS-e2e-ui-tests](https://github.com/Ouranosinc/PAVICS-e2e-ui-tests) yet.  @davidcaron, can you check if that [PAVICS-e2e-ui-tests](https://github.com/Ouranosinc/PAVICS-e2e-ui-tests) has a readme with how to run it and the procedure are up-to-date?  Thanks.
