### ISSUE TITLE
Finch explore subseting data using opendap url  

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#105]
Currently calculation of a climate index over a limited spatial area would require two wps steps

1. Subset  & writing to disk of original daily data
2. Calculation of climate index on newly created file

It could potentially be more efficient if the subset occurs in memory only without writing daily data to disk

This could potentially be achieved by using either the opendap querying :

http://test.opendap.org/dap/data/nc/sst.mnmean.nc.gz.ascii?time%5b0:6%5d  
more info here:
https://www.unidata.ucar.edu/software/thredds/current/tds/reference/NetcdfSubsetServiceReference.html

or maybe somehow integrating xclim's subset_bbox into finches climate index calls?

**Comment by huard** [comment]
See https://github.com/bird-house/finch/issues/20
