### ISSUE TITLE
Explore THREDDS logical file aggregation

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#107]
It's possible to aggregate multiple files into logical *dataset* (multiple variables and time periods from one simulation, an ensemble of multiple realizations, etc). 
Dealing with these logical aggregates might be easier when we'll try to build ensembles with constraints such as "need variables x and y available.". 

See https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/ncml/Aggregation.html

**Comment by huard** [comment]
@tlvu has done some testing with this, it's looking good so far. 
Question: can we override metadata attributes ? For example change variable names or units strings ?Add a version attribute ?

**Comment by tlvu** [comment]
@tlogan2000 can we close this issue?

**Comment by tlogan2000** [comment]
closing this, not that follow up will be found  here https://github.com/Ouranosinc/pavics-vdb/issues/1
