### ISSUE TITLE
Data url in opendap form

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#113]
The `Data URL` field in the `OPeNDAP Dataset Access Form` indicates `boreas.ouranos.ca` instead of the proxy address. 

See https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc.html

**Comment by huard** [comment]
> 
> Most TDS generated URLs are relative to the server (e.g., "/thredds/dodsC/") or relative to the the current document's base URL. There are only a few places where it is necessary to generate absolute URLs. In those cases, the TDS uses information from the incoming HTTP request to construct the generated URLs. It is up to the proxy to send the correct information to the proxied server so the request information will be correct.
> 
> For more information, see our web page on running Tomcat behind a proxy server. It contains links to Tomcat documentation on both mod_proxy and mod_jk as well as some user contributed documentation on setting up mod_proxy.

from https://www.unidata.ucar.edu/software/thredds/v4.3/tds/tds4.3/faq.html#CatalogURLs

**Comment by moulab88** [comment]
We can change the ContextPath in the config to have "/twitcher/ows/proxy/thredds/dodsC/" instead of "/thredds/dodsC" in the Data URL (tested on my dev machine). But still had problem with the Data URL port. I will review all the config (on the tomcat also).

**Comment by huard** [comment]
But then we short-circuit the authentication proxy. This could be a valid short term solution, but on the mid-term we want to be able to secure some data and processes.

**Comment by moulab88** [comment]
It will be behind the proxy:
https://www.unidata.ucar.edu/software/thredds/current/tds/reference/TomcatBehindProxyServer.html

**Comment by huard** [comment]
Fixed by @tlvu in https://github.com/Ouranosinc/PAVICS/pull/162
