### ISSUE TITLE
Store climex data on THREDDS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#114]
Store variables pr, tasmin, tasmax, tas, hurs from all climex realization over Qc on THREDDS data server.

- [ ] Propose file naming format and directory structure
- [ ] Propose chunking values
- [ ] Review and fix metadata for CF compliance
- [ ] Include "Terms of Use and Documentation" file
- [ ] Review
- [ ] Transfer

**Comment by huard** [comment]
For compliance checking
```bash
$ module load Anaconda
$ conda create -n compliance
$ mkdir src
$ cd src
$ git clone git@github.com:ioos/compliance-checker.git
$ pip install --user -r compliance-checker/requirements.txt
$ pip install --user msgpack 
$ pip install --user distributed
$ pip install --user ./compliance-checker

$ cchecker.py -l 
```

**Comment by cothel** [comment]
Ce sera un bon test pour certaines idées du chantier TITI. Quels types de fichiers seront distribués: séries temporelles et/ou fichiers de statistiques mensuelles?

**Comment by huard** [comment]
Cet issue ne concerne que les séries temporelles. On pourra en ouvrir un autre pour des stats et diagnostiques.

**Comment by moulab88** [comment]
Sur Neree l'environnement compliance est installé:
module load Anaconda
conda env list
source activate compliance
which cchecker.py
cchecker.py -l

**Comment by martinleduc** [comment]
Merci David. À noter que je vais revenir sur cet issue au retour de mes vacances début août.

**Comment by huard** [comment]
@martinleduc @mourad Statut ?

Notez que Long investigue la possibilité d'agréger et modifier les attributs via une couche virtuelle (ncml) sur THREDDS, ce qui nous éviterait d'avoir à modifier les fichiers originaux pour harmoniser les attributs.

**Comment by tlogan2000** [comment]
@martinleduc @huard il y a-t-il d'info de licence de données pour les jeux de données Climex? 
Présentment on a:  redistribution: Redistribution policy unknown. For internal use only.

**Comment by martinleduc** [comment]
Côté Bavière, LRZ distribue déjà publiquement les données ClimEx sur le domaine Europe, mais seulement pour un nombre limité de variables ayant déjà été validées, c.-à-d. [tas, tasmax, tasmin, pr, hurs], voir:

https://climex-data.srv.lrz.de/Public/     (voir CanESM2_driven_50_members/)

On devrait donc partager le domaine Québec selon les mêmes variables et conditions. À noter que les "Terms of use" contiennent toute l'information sur l'utilisation des données, tandis que la documentation de ClimEx donne des informations plus techniques. Ces deux documents sont partagés par LRZ "à côté" des données dans le sous-répertoire "Terms of Use and Documentation/" de la page plus haut.

Finalement, le fichier xml ci-joint contient plusieurs métadonnées officielles (qui seront éventuellement utilisées par LRZ comme une couche au-dessus de celle déjà implémentée dans les fichiers netcdf) concernant les créateurs et contributeurs aux données ClimEx, il y a aussi un lien vers une licence creativecommons.

[metadata.example.xml.txt](https://github.com/Ouranosinc/pavics-sdi/files/4330317/metadata.example.xml.txt)


 dans les fichiers netcdf.   

Il faudra aussi  qu'on informe la Bavière AVANT de mettre le tout en ligne pour avoir le ok.

Si on distribue d'autres variables que la liste plus haut, on devra se garder un petite gêne en attendant qu'elles soient validées, et donc conserver le "internal use only".

**Comment by Zeitsperre** [comment]
@martinleduc @tlogan2000 

Agnès and I have been trying to finalize a few suggestions for our current data and with, given the present context, I certainly have time to hammer out a modest proposal for Creative Commons (BY | BY-NC) for this week.

Is there an agreed-upon layout of fields for the attribution/licenses/TermsOfUse that Bavaria is using? Maybe it would be good if I spoke with you directly or though email to better understand.

Am I correct in assuming that the licensing decisions for CLIMEX Quebec fall on @martinleduc ?

**Comment by martinleduc** [comment]
@Zeitsperre Tu peux m'appeler si tu as des questions. Pour les décisions à propos des licences de ClimEx, je dois valider avec Anne qui doit à son tour valider avec Ralf de LMU qui est le PI du projet.

**Comment by huard** [comment]
On a le OK de Anne. 

For terms of use and credits, see https://www.climex-project.org/en/data-access

Terms of use: http://www.climex-project.org/sites/default/files/CRCM5ClimExRunsOuranos_TermsOfUse_Credits_eng_v6.pdf
Documentation: http://www.climex-project.org/sites/default/files/ClimEx_CRCM5-LE_documentation_v2.1.pdf
