### ISSUE TITLE
Install packages on JupyterLab environment

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#115]
The JupyterLab environment should include the following dependencies:

- ipywidgets
- IPython
- distributed
- xclim
- dask 

Note that the widget extension has to be enabled:
`jupyter nbextension enable --py widgetsnbextension`

**Comment by tlvu** [comment]
@huard From http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/94/artifact/environment-export-birdy.yml we already install `ipywidgets=7.4.2=py_0` and `ipython=7.5.0=py36h24bf2e0_0`.

From https://github.com/jupyter-widgets/ipywidgets/tree/master it says that `jupyter nbextension enable --py --sys-prefix widgetsnbextension  # can be skipped for notebook version 5.3 and above` and we currently have `notebook=5.7.8=py36_0`.

Can you test on https://pavics.ouranos.ca/jupyter what do not work for ipywidgets and IPython?

I will add xclim next week.

**Comment by huard** [comment]
If you look at interactive_wps notebook on jupyterlab, the execution should draw a progress bar.

**Comment by tlvu** [comment]
Seems to be problem with the Lab only, the old "notebook interface" works, see animated gif !  Try with this direct link https://pavics.ouranos.ca/jupyter/user/public/notebooks/interactive_wps.ipynb

![ipywidgets-working-for-notebook-only](https://user-images.githubusercontent.com/11966697/58742258-6ec0d900-83f1-11e9-9bee-869a275cc375.gif)

**Comment by huard** [comment]
Right. Found this: 
https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension
