### ISSUE TITLE
Make useful netCDF datasets available on PAVICS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#12]
- Select datasets most likely to be used in the coming year (Blaise décide unilatéralement)
- Copy them to THREDDS and index them in catalog 
- Set appropriate permissions
- Ask permissions to make restricted datasets public (David)
- Explain process in docs

A priori and unless someone finds this a really bad idea, I'd fill 80% of the "data" disk space with source data. When user space goes over 90% we buy new disks.

**Comment by huard** [comment]
Progress ? Timeline ? I'd like to know to be able to schedule demos. Thanks.

**Comment by bstdenis** [comment]
Progress: currently we have half of our standard scenarios, the scenarios produced for ArcticNet, the NRCAN gridded observations, and the hydrological projections from DEH.

Upcoming: second half of standard scenarios, 4 reanalysis (CFSV2, ERA Interim, JRA55, MERRA2)

Potential additional datasets: selection of CRCM5 simulations, mddelcc gridded observations, EC station data (point observations, not tested at all in the platform), ClimEx samples, CanESM2 Large Ensemble sample. But really, this can be anything we have...

Then the question remain as to what we do with our local CMIP5 & CORDEX archives, which could theoretically be obtained through esgf.

Timeline: Should we set some pace for data migration? e.g. 1 new dataset every week?

The procedure will involve checking (& possibly editing) all copied NetCDF files for sufficient metadata in the global attributes, (manually) copying the files to boreas, then running the crawler (working on some modifications to better target subdirectories, and investigating why the arcticnet scenarios were not properly catalogued).

**Comment by huard** [comment]
I'd say add the local CMIP5 and CORDEX data. A lot of work has been put into cleaning them. 
1 dataset/week sounds good. 
Let's not go over board with metadata editing. It's worth doing it for our own outputs, and the data that you yourself converted into netCDF, but not for upstream netCDF data. As long as the crawler works on them, I'm good. 
We'll add a CF-check process to flag problematic files on our todo list.

**Comment by huard** [comment]
Trevor, I'm not seeing much CMIP5 data nor observational data. Could you take over the effort to make data available on the server ? Let me know if you need help.

**Comment by huard** [comment]
Request from Jean-Luc Martel to have CMIP5 wind speed simulations on THREDDS. Jean-Luc would test drive the subsetting algorithms and provide feedback on usability. 

@Zeitsperre  Is this something that could be done for next week ?

**Comment by Zeitsperre** [comment]
I'm aiming to check a few things on my GIS working branch today and can look into starting a download from ESGF for wind speeds tomorrow. Unfortunately I will be out of the office from the 13th to the 19th, but I'll try to get a few things done during Monday.

Are there any particular models/groups/scenarios that we're interested in? How much data would we like to add?

**Comment by huard** [comment]
We should have wind data already on disk for winds (uas, vas). I suggest we start with those.

**Comment by Zeitsperre** [comment]
@huard I just started the upload process for all CMIP5 data we have for IPSL, NASA-GISS, and MPI-M. It should be finished over the weekend. I'll close this issue once this is confirmed on mine and your ends.

**Comment by Zeitsperre** [comment]
Looks good on my end. Good to close?

**Comment by huard** [comment]
Yep, thanks !
