### ISSUE TITLE
Use Intersphinx to include documentation from individual components

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#120]
Related to https://github.com/bird-house/birdhouse-docs/issues/38

Objective is to facilitate the build of the platform docs by linking to the docs of individual birds. This will scale better than try to build the docs from scratch for all the components. 

Note that we need to handle the fact that the platform runs a branch of each bird (not always master). So the docs for those branches need to be accessible.

**Comment by tlvu** [comment]
Can we leverage ReadTheDocs subprojects https://docs.readthedocs.io/en/latest/subprojects.html?highlight=subprojects?

"
Projects can be configured in a nested manner, by configuring a project as a subproject of another project. This allows for documentation projects to share a search index and a namespace or custom domain, but still be maintained independently.
"

**Comment by tlvu** [comment]
Intersphinx doc https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html do not mention anything about sharing search indexes between linked projects :(

**Comment by huard** [comment]
Don't know. Worth investigating. Would be a clean solution I think.

**Comment by huard** [comment]
Started work on branch fix-120.
