### ISSUE TITLE
Update FlyingPigeon to v1.5 in platform

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#125]
We're currently running an old version of FP. It's time we run the master to be in continuous deployment mode. 

Since we're losing the bias correction service, the canarie API will break. I've asked Dan to decommission this service starting on Sept 9th. So I suggest that in the meantime, we test FP, then on the 9th  change the branch to the latest tag in the docker-compose and redeploy.

**Comment by tlvu** [comment]
> to be in continuous deployment mode.

We are currently lacking the ability to automatically detect new version of upstream docker images published and automatically bring them into our stack.  Currently a human has to go check and manually commit the version update into the `docker-compose.yml` file.

FYI, this little feature is one of the little things we get for free if we are using Kubernetes. This specific feature is provided by https://www.weave.works/oss/flux/ a Kubernetes 3rd party tool.

**Comment by huard** [comment]
I think it's OK to keep manual control, but thanks for clarifying this.

**Comment by Zeitsperre** [comment]
The FP fork for Ouranosinc is fantastically broken at the moment, as the last updates I performed to were simply to push our changes across development branches (pavics-dev, pavics) to our master, before pushing those to upstream master. Do you see us working directly off of bird-house FP or are we going to modernize our fork?

**Comment by huard** [comment]
Directly off bird-house FP. We should archive our fork and let it rest.

**Comment by Zeitsperre** [comment]
FYI, the issues that remained in our FlyingPigeon fork have been closed and the repository has now been archived.

**Comment by huard** [comment]
Replacement. The old FP is causing too many problems. I want to close that chapter.

**Comment by huard** [comment]
@tlvu PyWPS will issue a new release over the next days, and FP will follow suit, pinning the latest PyWPS version. That will be our call to deploy the new FP.

**Comment by huard** [comment]
@tlvu FP 1.5 has been released.

**Comment by tlvu** [comment]
Pending dockerhub build https://github.com/bird-house/flyingpigeon/issues/296

**Comment by tlvu** [comment]
Close, fixed by PR https://github.com/Ouranosinc/PAVICS/pull/166
