### ISSUE TITLE
Data catalog refactoring

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#126]
The ESGF is working on a refactor of the data catalog and search interface, we should follow those efforts more closely and use this to modernize our own cataloging system, which at the moment does not integrate with the ESGF catalog (Blaise had a branch to do this, but it was not mature). 

So we need someone to take a look at work going on at ESGF and Copernicus and propose solutions that would meet the needs of DACCS for easy to maintain, federated searches. 

See for example: https://github.com/cedadev/archive-opensearch/tree/master/ceda_opensearch

Note that THREDDS can export metadata in the ISO 19115 format (https://www.unidata.ucar.edu/software/tds/current/reference/ncISO.html), a format which I believe is understood by OpenSearch. In principle, we would have a pathway to export and ingest metadata using off-the-shelf software. However, it does not be default export all fields in the metadata of netCDF files, which is problematic for us. 

Couple of issues we should look into: 
- Fast crawler
- OpenSearch interface for catalog
- Search can return results from aggregated opensearch catalogs. 
- Configure to have two layers: raw and aggregated (NcML)
- Search results can be exported in intake-esm compatible format. 
- Reduce internal code footprint

**Comment by tlvu** [comment]
> So we need someone to take a look at work going on at ESGF and Copernicus

I am interested but I do not have enough understandings of large scale data management / Thredds.

I just would like to be keep in the loop if any progress/discoveries.

**Comment by huard** [comment]
Superseded by Intake and STAC efforts.
