### ISSUE TITLE
Update route regexes for different service stats

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/pavics-sdi#127]
Basically, the current route regexes are not distinct so some routes are eating the stats of other routes so we see zero usage for some routes, which is not true.

See #118 for more details, especially comment https://github.com/Ouranosinc/pavics-sdi/issues/118#issuecomment-523636469 and comment https://github.com/Ouranosinc/pavics-sdi/issues/118#issuecomment-524416628

**Comment by huard** [comment]
Stats need to work for our next VC with Canarie on Sept 17.

**Comment by tlvu** [comment]
Alright, I can submit a basic patch, improve later if you need to.
