### ISSUE TITLE
Thredds: Opendap link provided by http works only inside VPN

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#128]
The http interface of the THREDDS server provides an OPeNDAP link that works inside the VPN, but not outside... That means external users need to manually convert the links they copy-paste. 

For example this is an internal link

http://boreas.ouranos.ca:8083/thredds/dodsC/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc
and this would be the corresponding external link:

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc

**Comment by tlvu** [comment]
Finally found out, it's twitcher that is eating the http header that Nginx is passing to Tomcat.

Below is Nginx proxying directly to Tomcat (Thredds) without twitcher in the middle.  We see the host name is being passed properly, I just have to find how to pass the proto (httpS) as well.

![2019-09-16-180801_1014x481_scrot](https://user-images.githubusercontent.com/11966697/64996995-6eb7ec80-d8ad-11e9-89ac-8174b74046eb.png)
