### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#134]
pavics.ouranos.ca leads to the UI which is not really in working order (with all the test project names, it looks weird). 

Question is, where should pavics.ouranos.ca point to ?

**Comment by tlvu** [comment]
> with all the test project names, it looks weird

Clean up those test project names, make them more presentable?  Even if we point `pavics.ouranos.ca` elsewhere, isn't this step still useful?

**Comment by tlogan2000** [comment]
Short term I would say re-direct to the Jupyter hub. Longer term I think we would minimally want to setup a landing page with info about the platform, links to the Jupyter instance, terms-of-use, licencing info, potentially a dataset description section

**Comment by tlvu** [comment]
Close: fix by Pr https://github.com/Ouranosinc/PAVICS/pull/189

**Comment by tlogan2000** [comment]
Sorry for reopening ... small detail but I think organizing the various user folders into a single 'users' header folder would be a good idea in order to guide people towards the most useful examples

**Comment by tlvu** [comment]
Moved all the user folders under `users/`:

![2019-12-02-145541_945x473_scrot](https://user-images.githubusercontent.com/11966697/69990619-070c5780-1514-11ea-951b-10a77bd96fc6.png)

![2019-12-02-145555_943x437_scrot](https://user-images.githubusercontent.com/11966697/69990631-0a074800-1514-11ea-9c7f-dd66df9a71cf.png)

What do we do with the `interactive_wps.ipynb` and `launching a cluster.ipynb` files?  If they are useful enough can we commit them with the `README.ipynb` or move their content into `README.ipynb` file?  Then we will be zesty clean :D

**Comment by huard** [comment]
I think we can scrap them for now.

**Comment by tlvu** [comment]
> I think we can scrap them for now.

If you do not object @tlogan2000 I will scrap them tomorrow and close this issue.

**Comment by tlvu** [comment]
`interactive_wps.ipynb` and `launching a cluster.ipynb` are scrapped.

Closing issue.
