### ISSUE TITLE
JupyterLab plugins and extensions

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#141]
* Get a sense of JupyterLab plugins and extensions that would support the workflow we're envisionning for users. 
* Install them
* Document their usage

Potential plugins / extensions for our consideration: 
* [x] https://github.com/jupyterlab/jupyterlab-git
* [x] https://github.com/jupyterlab/jupyterlab-google-drive
* [ ] Intake GUI https://intake.readthedocs.io/en/latest/gui.html
* [ ] https://github.com/eWaterCycle/jupyterlab_thredds/tree/v0.4.0
* [ ] https://github.com/dask/dask-labextension

Easy 
* [ ] https://github.com/hadim/jupyter-archive
* [ ] https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559
* [ ] jupyterlab-clipboard

**Comment by tlogan2000** [comment]
I would add these for creating interactive graphs and maps
- [ ] https://github.com/jupyter-widgets/ipywidgets
- [ ] https://github.com/plotly/plotly.py
- [ ] https://github.com/plotly/jupyterlab-chart-editor
- [ ] https://github.com/jupyter-widgets/ipyleaflet

**Comment by tlogan2000** [comment]
Added  https://github.com/plotly/jupyterlab-dash to the list... It might be a more cohesive solution than using a combination of  Ipywidgets / plotly for the graphing callbacks

**Comment by tlogan2000** [comment]
This might be useful once we have nailed down the legal terminology to create a checkbox accepting terms and conditions etc: 

https://github.com/ResearchComputing/jupyterhub-options-spawner

**Comment by huard** [comment]
@tlvu I have a fairly urgent need for a git plugin. I realized that I cannot bulk download the notebooks I'm developing for a workshop, and I'd like to version control them before giving the password to external collaborators.

**Comment by huard** [comment]
For the moment, I'm making a tar and downloading that, so if it's not possible to install the git extension quickly, I have some options.

**Comment by huard** [comment]
jupyterlab-clipboard

**Comment by episodeyang** [comment]
@huard did you get your urgent need solved in time?

**Comment by huard** [comment]
I did, thanks!

**Comment by tlvu** [comment]
2 other plugins from discussions with @tlogan2000 

https://github.com/hadim/jupyter-archive

https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559

**Comment by tlvu** [comment]
@huard is this https://github.com/Bamieh/jupyterlab-clipboard the one you wanted?  It's not installing properly

```
Node v13.13.0

Yarn configuration loaded.
> /opt/conda/envs/birdy/bin/npm pack jupyterlab-clipboard
npm notice
npm notice 📦  jupyterlab-clipboard@0.3.0-alpha
npm notice === Tarball Contents ===
npm notice 670B  lib/clipboard.js
npm notice 2.3kB lib/dialogs.js
npm notice 6.0kB lib/image-editor.js
npm notice 5.3kB lib/index.js
npm notice 1.3kB package.json
npm notice 1.2kB README.md
npm notice 93B   lib/clipboard.d.ts
npm notice 232B  lib/dialogs.d.ts
npm notice 487B  lib/image-editor.d.ts
npm notice 129B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-clipboard
npm notice version:       0.3.0-alpha
npm notice filename:      jupyterlab-clipboard-0.3.0-alpha.tgz
npm notice package size:  5.0 kB
npm notice unpacked size: 17.7 kB
npm notice shasum:        cc0df959ab42c2b8244fcf8469ebeecb0fc1ce92
npm notice integrity:     sha512-88dVN6QCsmW2R[...]RcG6Yr+cCYCLQ==
npm notice total files:   10
npm notice
jupyterlab-clipboard-0.3.0-alpha.tgz

Fetching URL: https://registry.yarnpkg.com/jupyterlab-clipboard
Fetching URL: https://registry.yarnpkg.com/jupyterlab-clipboard
Traceback (most recent call last):

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/opt/conda/envs/birdy/lib/python3.7/site-packages/jupyterlab/commands.py", line 1550, in _install_extension
    raise ValueError(msg)

ValueError: The extension "jupyterlab-clipboard" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=4.1.0 <4.2.0          >=2.2.1 <3.0.0 @jupyterlab/coreutils
>=2.1.2 <2.2.0          >=0.19.3 <0.20.0@jupyterlab/filebrowser
>=2.1.2 <2.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook
>=5.1.0 <5.2.0          >=3.2.1 <4.0.0 @jupyterlab/services

Exiting application: jupyter
```

**Comment by huard** [comment]
Doesn't seem to be maintained anymore... forget it then.

**Comment by tlvu** [comment]
The `devel` image on Medus has the rest of the "need to devise a proper workflow" plugins, except `jupyterlab_thredds` plugin that seems to not support latest JupyterLab 2.0 yet (see commit 056516fe311ea86a13b46b0ff8cc82d887728567).

**Comment by tlvu** [comment]
These 2 looks interesting, adding them to the `devel` image to see
https://github.com/jupyterlab/jupyterlab-toc
https://github.com/jupyterlab/jupyterlab-commenting

**Comment by tlvu** [comment]
The `devel` image is built from this branch https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commits/devel-new-extensions.  This branch should not be merged, it's done for quick prototyping (lots of little layer), not the clean way (least number of layers possible).
