### ISSUE TITLE
Evaluate ESMValTool 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#145]
Is it a good fit for Ouranos ? Would it be useful as a framework to run diagnostics ? Evaluate regional models ? 

https://www.researchgate.net/publication/337546601_ESMValTool_v20_-_Extended_set_of_large-scale_diagnostics_for_quasi-operational_and_comprehensive_evaluation_of_Earth_system_models_in_CMIP

**Comment by huard** [comment]
Assess alongside PCMDI Metrics package

**Comment by sbiner** [comment]
Anne m'a appris l'existence de la chose tantôt. Je vais essayer de regarder ça avant notre rencontre vendredi PM.

**Comment by huard** [comment]
@sbiner Statut ?

**Comment by sbiner** [comment]
@huard J'ai regardé ça rapidement. 

Ça semble assez puissant, il y a une intégration de synda et d'autres outils permettant d'aller chercher des données dans différentes BD. Par contre l'installation de tout ceci ne semble pas trivial du tout. C'est comme un wrapper qui permet d'utiliser de manière unifiée des recettes qui elles sont en différents languages (python, ncl, ...).

Je ne sais pas trop quoi dire d'autres. Pour moi c'est un outil permettant de refaire de manière systématique des diag et figures qu'on fait souvent. Il me semble que les différentes équipes ont déjà cette capacité ... et ça ne semble pas particulièrement friendly user.

Par contre, c'est un projet bien vivant, contrairement à RCMES et je pense qu'on pourrait l'utiliser pour des diagnostiques de MRCs.

**Comment by huard** [comment]
@sbiner  Question: est-ce que selon toi et ton équipe, ça vaut la peine qu'on investisse du temps là-dedans ?
Est-ce que par exemple on demande à Mourad de faire une installation locale pour poursuivre l'exploration ?
