### ISSUE TITLE
Revise README to reflect the fact that jupyter now has private workspace

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#151]
The current README says: 

> This JupyterLab is not meant as a production environment. It is a public server with no private directory. Your files are public, can be seen by the rest of the world and can be reset at anytime. Use it to explore the system's capability and see whether it may be useful to your work. If it is, install the `birdy` client locally along with software to read netCDF files and you're set to go.

**Comment by tlvu** [comment]
The actual README file to edit is in birdhouse-deploy repo: https://github.com/bird-house/birdhouse-deploy/blob/master/docs/source/notebooks/README.ipynb
