### ISSUE TITLE
Update finch notebook

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#156]
Finch 0.4.1 breaks finch notebook.

**Comment by tlvu** [comment]
Can we take this opportunity to keep only one of https://github.com/Ouranosinc/pavics-sdi/blob/master/docs/source/notebooks/finch.ipynb and https://github.com/bird-house/finch/blob/master/docs/source/notebooks/finch-usage.ipynb.

I vote to keep the one in the Finch repo and remove the duplicate one in Pavics-sdi.  Else we'll need to double fix the notebooks for each change.

**Comment by huard** [comment]
Good point, will do.

**Comment by tlvu** [comment]
Finch notebook in Finch repo fixed in PR https://github.com/bird-house/finch/pull/112

Remaining work: delete the duplicate Finch notebook in pavics-sdi.

**Comment by tlvu** [comment]
@huard Humm the code is the same but the explanation text is slightly different between the 2 duplicated notebooks. 

I was going to just delete the pavics-sdi one but now I think I'd rather let you review the explanation difference and "backport" them if needed.
