### ISSUE TITLE
Security certificate for pavics.ouranos.ca

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#16]
This server could not prove that it is pavics.ouranos.ca; its security certificate is from boreas.ouranos.ca. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by moulab88** [comment]
Done. 
Temporary certificate expires on 21/05/2018. May be buy one permanently.

**Comment by huard** [comment]
Ça marche ! Merci.
