### ISSUE TITLE
Configure, deploy and test THREDD viewer extension

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#162]
See https://pypi.org/project/jupyterlab-thredds/

Decide whether to include or not based on experience.

**Comment by huard** [comment]
@tlvu j'ai l'impression que tu avais déjà regardé ça, et que ce n'était pas compatible avec la version de JupyterLab qu'on utilise. Est-ce que ça te dit qqch ?

**Comment by tlvu** [comment]
> @tlvu j'ai l'impression que tu avais déjà regardé ça, et que ce n'était pas compatible avec la version de JupyterLab qu'on utilise. Est-ce que ça te dit qqch ?

Me semble que oui.  On pourrait le re-tester, ça pourrait avoir changé.

**Comment by huard** [comment]
Semble pas être maintenu, je ferme.
