### ISSUE TITLE
Experiment running xclim and Finch on AWS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#175]
There is now a subset of CMIP6 on AWS S3, and we have an account to run CMIP6 related experiments on AWS.

I suggest we 
1. Experiment with running xclim notebooks on AWS;
2. Experiment with running Finch on AWS;
3. Report findings

**Comment by tomLandry** [comment]
Sounds great. @dbyrns for your info, the AWS S3 account mentioned here is ESGF and CRIM is also registered for use.

**Comment by huard** [comment]
Pascal wrote a notebook showing how to run a cluster on AWS driven by a local instance, operating on CMIP6 data stored at AWS. 
In the tests, performance was under what we achieve with PAVICS.
