### ISSUE TITLE
Installation docs outdated

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#18]
https://github.com/Ouranosinc/pavics-sdi/blame/master/docs/source/dev/installation.rst#L30

I'm following along to try and build pavics via docker-compose. Issue arises with pointing to birdhouse folder not included in pavcs-sdi. Is this suggesting that birdhouse should already be in place with birds preinstalled via git clone? 

Should there be a command somewhere to build the docker-compose image at some point before cloning pavics-sdi? Very confused.

**Comment by huard** [comment]
Has this been sorted out ? Can't really help you there. I suggest asking Mourad or Blaise.
