### ISSUE TITLE
Method for accepting terms and conditions 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#188]
I would like to have an automated way for users to accept terms and conditions and privacy policy (in prep)

This would seem to be a likely candidate but seems relatively unmaintained (@tlvu couldn't install due to out of date dependcies etc etc)  

https://github.com/ResearchComputing/jupyterhub-options-spawner

**Comment by huard** [comment]
Could we say that "by logging into the platform you accept the terms and conditions" ?

**Comment by tlogan2000** [comment]
> Could we say that "by logging into the platform you accept the terms and conditions" ?

This could be our plan B I suppose.  I don't really want major effort put in but I think an 'active' acceptance by users is more legally sound (according to agnes).   When Christian starts we could maybe see what could be done with custom login page templates https://jupyterhub.readthedocs.io/en/stable/reference/templates.html  ..   He might be able get something done in little time / effort

**Comment by tlvu** [comment]
There is an open issue about making the login page more customizable.  Currently people have to hack the source code directly, which means it's less maintainable, see https://github.com/jupyterhub/jupyterhub/issues/1385#issuecomment-326966823 and the improved login page https://jupyter.brynmawr.edu/hub/login using direct source code hack.

**Comment by tlvu** [comment]
Discussed with @tlogan2000, will try to hack the login page so that user have to check the checkbox "By logging in, you agreed to our terms and conditions" for the login button to be active.

The actual terms and conditions text will be a link to a `.md` file on github so any update is easily diff-able to user.

**Comment by tlvu** [comment]
I got it !  https://lvupavics.ouranos.ca/jupyter/hub/login

![recorded](https://user-images.githubusercontent.com/11966697/99327962-1aa9ee80-2849-11eb-9ce8-3be6a1484e94.gif)

Left to prepare a clean patch to submit to JupyterHub.

The prototype points to some random README.md file.  We can easily replace that link.

**Comment by tlogan2000** [comment]
@tlvu perfect.
