### ISSUE TITLE
Intermittent Jupyter restart failures

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#190]
When shutting down and restarting jupyter server an error is occurring (intermittent but fairly regularly).
``
Spawn failed: 500 Server Error: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit") 
``

what I did: Access Hub control panel (file > hub control panel)
click 'stop' button (successful shut down)
click 'start' button (results in error message above)

**Comment by tlvu** [comment]
Support request sent to DockerHub: Docker Support [Request received] - Getting "You have reached your pull rate limit." but we already paid our Team licence (#23152)

![Screenshot from 2020-11-23 14-29-11](https://user-images.githubusercontent.com/11966697/100006937-44a76780-2d99-11eb-9235-f504f2fa77a1.png)

**Comment by tlvu** [comment]
I've applied for the open-source application so the pull rate-limit is lifted for non-authenticated users for our repos.

=======================

From: Support <hub-support@docker.com>
Sent: Tuesday, November 24, 2020 19:03
To: Vu , Long
Subject: [Docker Support] Pending request: Getting "You have reached your pull rate limit." but we already paid our Team licence

##- Please type your reply above this line -##

Hi,

This is an email to remind you that your request (#23152) is pending and awaits your feedback.

[https://dockerhelp.zendesk.com/system/photos/3605/9864/8091/profile_zoom.jpg]

Brett (Docker Support)

Nov 23, 2020, 15:00 PST

Hi Vu

Please note that a Team plan entitles each person in the team to unlimited pulls. Pulls are tracked per-user, not based on the image or image namespace (organization). You will need to authenticate your pulls with your user accounts to avoid limits. We have instructions for many systems here: https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests

If you're distributing software for your customers through Hub, we do have partnership options for whitelisting namespaces: https://www.docker.com/partners. If you're an open source organization we also have programs for that: https://www.docker.com/community/open-source/application

Thanks,
Brett

**Comment by tlogan2000** [comment]
Excellent

**Comment by tlvu** [comment]
The pull rate limit should be lifted in a few days.  Closing this issue.

________________________________________
From: William Quiviger <william.quiviger@docker.com>
Sent: Wednesday, December 2, 2020 10:42
To: Vu , Long
Cc: William Quiviger; dockerhub-admin; Huard , David; Logan, Travis
Subject: Re: Your application has been approved

Hi Vu,

duly noted, I’ll make sure I correct the mistake.

The whitelisting should take a few days to come into effect.

Best,

William
