### ISSUE TITLE
Reduce THREDDS response time

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#196]
```
ds = xr.open_dataset("https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/forecasts/eccc_geps/GEPS_latest.ncml")`
```
takes about 5-6 seconds on my machine to complete. How do we know where time is spent and if we can improve speed ?

**Comment by tlvu** [comment]
Might be related to https://github.com/bird-house/twitcher/issues/97

**Comment by huard** [comment]
Much faster now, closing.
