### ISSUE TITLE
Document GeoServer administration 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#2]
Add material in docs/source/dev/geoserver.rst

**Comment by Zeitsperre** [comment]
see #11

**Comment by bstdenis** [comment]
FYI, I used the tutorial here: http://docs.geoserver.org/stable/en/user/gettingstarted/shapefile-quickstart/index.html to add shapefiles to our geoserver.

**Comment by huard** [comment]
Unfinished sentence:

Adding data to GeoServer
There are two possible methods for loading data sets into a store in GeoServer: using SCP/SSH or with QGIS GeoServer Explorer. Both require write access credentials to the GeoServer Administrator panel. Employing SCP/SSH is a more manual method and the ???

**Comment by Zeitsperre** [comment]
Issue addressed in 60d83ac11f107a53d1a7023d1ae8d582a04a72f7
