### ISSUE TITLE
XKCD matplotlib fonts on PAVICS

### ISSUE THREAD

**Issue by JeremyFyke** [Ouranosinc/pavics-sdi#204]
I’m trying to make some illustrative plots (actually, IDF teaching plots for climatedata.ca's Learning Zone) and I’d like to use the [XKCD plotting package within matplotlib](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xkcd.html) to generate some illustrative, fun plots that - most importantly - don’t scare people.  

When I run this I receive:

**findfont: Font family ['xkcd', 'xkcd Script', 'Humor Sans', 'Comic Neue', 'Comic Sans MS'] not found. Falling back to DejaVu Sans.**

How can I download these font families (and/or more generally, other font families to match various font requirements) on PAVICS?

Thanks!  And apologies if this is the wrong forum to post this request.

Jeremy Fyke

**Comment by aulemahal** [comment]
Interesting question! Haha, not scaring people is quite a good idea.
First off, there might be an easy way, @tlvu?
How easy is it to either : 
1) install a font package in the docker image 
or 2) manually install a font in the docker.

However, I did found a manual way to use xkcd() on Pavics without need for admin rights.
Linux stores fonts in a couple of directory, including `~/.fonts` for user-dependent ones. So:

- Download the xkcd fonts from [here](https://github.com/ipython/xkcd-font/tree/master/xkcd/build) (no idea if this is an officiel repo or not, just the first search results I got).

- Upload the otf files to your pavics workspace.
- In a notebook, run the following commands. We are using jupyter's "magic" methods to run shell commands with the "!" prefix.
```
!mkdir ~/.fonts   # Create a local fonts directory
!mv *.otf ~/.fonts  # move the uploaded fonts
!ls ~/.fonts/  # Just to check if it worked
!rm -fr ~/.cache/matplotlib  # Remove matplotlib's cache.
```
The last line isn't elegant, but it seems there is no easy way to reset matplotlib's font cache. 

- Restart the jupyter server (in File -> Hub control panel,  stop the server, wait and relaunch a new one).

The last step might not even be needed, I don't know. I'm pretty sure you at least need to restart the kernel. This should work for all fonts.

**Comment by JeremyFyke** [comment]
Hey this works!  Thanks for looking into this so rapidly Pascal!
![IDF-CC-interactive5](https://user-images.githubusercontent.com/4965999/109905186-419efb80-7c53-11eb-8e19-e4d625fe90e0.png)

**Comment by tlvu** [comment]
Is there a Pip or Conda package for those XKCD font?  I only found this https://github.com/xerosanyam/Fonts-xkcd.  I'd much prefer proper packaging if such exists.

**Comment by aulemahal** [comment]
Sadly I don't think pip is able to install fonts. Conda might be able, but there is no package for this right now.

**Comment by tlvu** [comment]
> Sadly I don't think pip is able to install fonts. Conda might be able, but there is no package for this right now.

Right, Pip is clearly not for fonts.  I was thinking too narrowed to the `environment.yml` file which handle both Pip and Conda.  But I can use `.deb` packaging as well (the docker image is Debian based).

**Comment by tlvu** [comment]
Oh found https://stackoverflow.com/a/49408754 (`sudo apt install fonts-humor-sans`).  I'll see how it goes.  @JeremyFyke you have a sample notebook for me to use as test?

**Comment by aulemahal** [comment]
Wrong button sorry. I have one I can send you.

**Comment by JeremyFyke** [comment]
My notebook is a bit convoluted to use as a tester (does a bunch of data access and manipulation too you'd have to sort out to get to run. I suggest just trying to replicate the matplotlib toy example..?
