### ISSUE TITLE
Git jupyterlab-extension is creating too many processes

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/pavics-sdi#205]
It has happened twice now, that @moulab88 writes me because Boréas is overwhelmed by "git-remote-http" processes.
I did use the git extension both times. Last time only for 2 commits dans 2 pushes.
I saw nothing on the base plugin repo (https://github.com/jupyterlab/jupyterlab-git), but I only skimmed it quickly.

**Comment by huard** [comment]
Has this reoccurred ?

**Comment by aulemahal** [comment]
Not to my knowledge. I stop using the extension shortly after this issue and because of the Github/SSH issue, I have only  used it once or twice since.
