### ISSUE TITLE
New package required to access ERA5 data directly on google cloud through pangeo intake catalog

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/pavics-sdi#223]
The following package would be required on the JupyterLab Env so that we can access the zarr intake format:

conda install intake-xarray

I am unsure how to perform this on the server instance. 

Thanks!

**Comment by tlvu** [comment]
> I am unsure how to perform this on the server instance.

@richardarsenault You can use the jupyter-conda plugin to add it temporary to your Jupyter server right now to unblock you.

intake-xarray will be added to the next build of the Jupyter server.

**Comment by tlvu** [comment]
@richardarsenault new Jupyter env containing `intake-xarray` is released.  Restart your Jupyter server to get it.

**Comment by richardarsenault** [comment]
it works, thanks!
