### ISSUE TITLE
Finch max filesize limit is set to 100MB - too small for extracting ERA5 data

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/pavics-sdi#226]
The ERA5 data (and eventually ERA5-Land data) cannot be averaged at the basin scale using finch.average_polygon(), because the filesize limit is set at 100MB. I am currently working with reasonably-sized catchments and have ERA5 files in the 200-300MB range.

Is there a way to override this limit?

Thanks!

**Comment by huard** [comment]
Yes, we'll need to deploy a new version with the new config though.

**Comment by huard** [comment]
@richardarsenault Could you share an example of the code you're using to do that?

**Comment by huard** [comment]
Is it the 05_Extracting_external_data nb ?

**Comment by Zeitsperre** [comment]
Just an FYI, but I'm downloading a new set of ERA5-Land files that will be divided by months and chunked better. Hopefully all will be said and done by next week.

**Comment by richardarsenault** [comment]
@huard actually I removed the call to finch in the notebook because of the error. I use clisops subset now, but for some features I am sure finch would be better.  Basically I extract a bounding-box around a catchment to extract ERA5 data and save it to netcdf, then I use average_polygon to average the data over the watershed. But the netcdf is like 250MB, and I get the error that the limit is 100MB.

**Comment by huard** [comment]
Ok, I think you have the right strategy: subset_bbox then average_shape over the selection. However, my suggestion would be to do the subset "in memory", and avoid downloading the subset locally then sending it back to the server for averaging. My sense is that this is something that should be done in clisops directly. 

@aulemahal Thoughts ?

**Comment by huard** [comment]
@aulemahal In particular, do you think xESMF and dask are smart enough to avoid requesting the full grid to compute the dot product ?

**Comment by richardarsenault** [comment]
Actually I tried doing so (passing a xarray dataset that is loaded in memory locally on the jupyterlabs instance) to finch commands and I always got weird errors. Not sure I am using the correct approach though... if there are ways to do this without creating netcdf files locally that would be perfect!

**Comment by aulemahal** [comment]
>  In particular, do you think xESMF and dask are smart enough to avoid requesting the full grid to compute the dot product ?

Sadly no, because it uses apply_ufunc with the spatial dims as "input core dims", thus forbidding chunking along thoses axes. Moreover, the current flattened way the weights are stored in xESMF would make this a bit complicated. The recent addition of `sparse` (instead of direct `scipy.sparse`), might open the door to improvements in this direction.

> My sense is that this is something that should be done in clisops directly.

I think this makes the most sense. Transforming the xESMF weights into a 3D (lat, lon, poly) array (`sparse` or `numpy`) and subsetting both input data and the weights according to the non-zero areas. Then taking the dot product.

**Comment by huard** [comment]
I meant doing a simple subset_bbox before calling the SpatialAverager, so that weights are themselves defined on a spatial subset. What you are proposing is fancier, but would require more work.

**Comment by aulemahal** [comment]
Oh! Well your solution is way easier indeed!

**Comment by huard** [comment]
https://github.com/bird-house/birdhouse-deploy/pull/195
