### ISSUE TITLE
Can't close PAVICS-frontend panes via check-box

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#23]
I realize that within the PAVICS-frontend interface, I haven't been able to close panes by clicking on their upper-right corner check-box. Only clicking the on the option-wheel in the bottom left of the screen allows me to open and close panes.

I have tried performing the same actions on other servers and same results. I've also attempted this using some VMs I had on hand (Ubuntu 16.04, openSUSE Tumbleweed, Arch) with same results. Everything seems to work fine on Windows, so it may be OS-related.

![screenshot from 2018-03-15 13-37-59](https://user-images.githubusercontent.com/10819524/37480654-29b41770-2856-11e8-87a3-76e65a0118ab.png)

**Comment by huard** [comment]
Seems to work now.

**Comment by Zeitsperre** [comment]
Problem still present on my side for Debian and Ubuntu systems running Firefox. What are you running?

**Comment by huard** [comment]
Chromium

**Comment by Renaud009** [comment]
This is a known issue. Browser related and not OS related. Just found a quick solution without having to update MaterialUI package. The triggered action should be on the button and not the icon.

**Comment by Renaud009** [comment]
https://github.com/Ouranosinc/PAVICS-frontend/pull/83
