### ISSUE TITLE
Implement bias-correction service

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#24]
Here is a branch: https://github.com/huard/flyingpigeon/tree/kddm_bc

What I haven't checked so far is whether or not it installs correctly, ie all dependencies are listed.

**Comment by Zeitsperre** [comment]
@huard, I just tried to install this in an Ubuntu LTS vm. In a fresh system, installation fails. Errors and warnings:

- Deprecation warning concerning ez_setup (I've seen this before in other birds, so I imagine this is fine.)
- Deprecation warning concerning Pandas call: Pandas.core.datetools should change to--> Pandas.tseries
- Installer looks for a module called ".wps_kddm_bc" and throws an ImportError as it isn't preinstalled. 

It then publishes a stacktrace for zc.buildout recipe errors and the install fails. Snappy, Anaconda, Java, and eggs seem to install fine. Is your PyWPS where I can find ".wps_kddm_bc"

**Comment by Zeitsperre** [comment]
It also demands 'curl' before the install can get off the ground, but that's more of a system-specific library that should be installed already. Should it be included in requirements?

**Comment by huard** [comment]
Well, that's me going too fast... I had forgotten to add the actual core files to git. How about now ?

**Comment by Zeitsperre** [comment]
Ran a clean install. All errors resolved and GetCapabilities returns functions that include KDDM wps definitions. Looks good.
