### ISSUE TITLE
Distinguish between original data and data on which operations have been made

### ISSUE THREAD

**Issue by bstdenis** [Ouranosinc/pavics-sdi#25]
The issue is that searching the catalog for (e.g.) a given simulation for a given model also returns files that are derived from that dataset (e.g. various subsets, or other operations that do not alter variable facets).

The easy solution would be to tag all derived data using a single facet (e.g. derived=true). This should be in the derived NetCDF files global attributes, and so it involves either modifying all processes (not practical) or to add this operation to our publish mechanism (note that recently the wps_outputs directory was removed from the catalog crawler, so those files are not searchable until they are published.)

The more complicated solution (but more descriptive in terms of metadata) would be to have appropriate facets change as operations are made, e.g. domain=Quebec after a subset. This would also require changing many processes, or a more strict publishing process.

**Comment by huard** [comment]
If processes correctly modify the file metadata, and we run the crawler on the newly created dataset, in principle the "new" properties should be captured in the DB, no?

**Comment by bstdenis** [comment]
Yes, as long as all those new properties are known facets (there's a default list in pyPavics catalog.py, and a hardcoded list in the crawler WPS process in PAVICS-DataCatalog). Alternatively, the crawler could accept facets inputs and allow the addition of new facets on the fly.

**Comment by huard** [comment]
Does the crawler write to netCDF at the same time? If not, the issue I see is that if these facets are not within the netCDF metadata, if you recrawl and overwrite the DB, you lose the information that you dynamically entered within the process? 

I tend to think that the database should miror the file content, and not depend on how the files got there (the history) ?

**Comment by bstdenis** [comment]
I agree, the crawler does not write to NetCDF. However the publisher copies the file to an "official" directory, so I think that would be the appropriate time to add missing facets to the file.

Again, in a perfect world, each process would modify the facets according to the modification it made to the data.
