### ISSUE TITLE
Regrid process + CANARIE registry

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#27]
Pull the regridding process from birdhouse/flyingpigeon into PAVICS. Connect service to CANARIE registry.

**Comment by Zeitsperre** [comment]
I'm having some issues performing this. Documentation for pulling commits or files from remote branches into a local one isn't very clear. 

My approach is to add the remote bird-house/flyingpigeon master branch and attempt to pull files or commits from it tp push into Ouranosinc/flyingpigeon. I've tried pulling select files from the remote as well as pushing files from within the branch (but this doesn't work as there are no changes to commit while within the branch). I don't suppose stashing is the best method either. Pulling commits ("cherry-picking") also throws errors as I imagine the files being modified are not the same between local--remote.

Have you performed this before? Would it be better if I simply copy-pasted the relevant lines in __init__.py and moved over the wps_regrid.py manually?

**Comment by Zeitsperre** [comment]
For more info: https://stackoverflow.com/questions/2364147/how-to-get-just-one-file-from-another-branch

**Comment by huard** [comment]
Yeah, my instructions were crap. I ended pulling the entire master branch from birdhouse, and that's how we should proceed in general, not try to cherry-pick stuff. If there are new processes in birdhouse that we don't want, we pull the upstream master, kill the file in the pavics branch, commit and that's it. 

Done in branch pavics-dev. I'll leave you to check it looks good. I guess the idea would be to include the bias correction process in pavics-dev, do a test deployment, then push it on pavics and ask Mourad to deploy it on boreas. Then work on the CANARIE registry for these two services. 

It's not a big deal for now if everything crashes, we are the only users.

**Comment by Zeitsperre** [comment]
To clarify, this would mean to do the following:

- Migrating the files pertaining to the bias correction process (kddm?) from huard/flyingpigeon/master branch (the one I merged the other day) to the Ouranosinc/flyingpigeon/pavics-dev branch; 

- Building the modified pavics-dev branch and verifying that it runs;

- Pushing/merging changes from Ouranosinc/flyingpigeon/pavics-dev towards Ouranosinc/flyingpigeon/pavics;

-  Asking Mourad to load the new 'pavics' branch on Boreas.

Just want to be certain. I'd rather not be responsible for us having to rollback significant changes.

**Comment by Zeitsperre** [comment]
Checking it out now. Thanks for the clarifications/explanations!

**Comment by Zeitsperre** [comment]
Merges performed and building without errors [https://github.com/Ouranosinc/flyingpigeon/commit/4cc3394117bfc64c8f59fc748382a6b1a0d7f972#diff-380c6a8ebbbce17d55d50ef17d3cf906]

@moulab88, could you load the new 'pavics' branch (https://github.com/Ouranosinc/flyingpigeon/tree/pavics) on Boreas?
