### ISSUE TITLE
Combine PAVICS search with ESGF search

### ISSUE THREAD

**Issue by bstdenis** [Ouranosinc/pavics-sdi#29]
Write a WPS that combines the Solr response from the ESGF search with the Solr response from the PAVICS search.

One outstanding issue is the availability of OPEnDAP/WMS links in ESGF. Since these protocols are not always available, should there be a fallback to the fileserver as much as possible, in which cases? Do we allow a mix of OPEnDAP link and fileserver links as inputs to WPS (this is already possible in some processes that use the opendap_or_download function (see https://github.com/Ouranosinc/flyingpigeon/blob/pavics/flyingpigeon/handler_common.py).

**Comment by huard** [comment]
Let's start with the simplest case (fileserver links), and try to move generic support for all kinds of netCDF interfaces upstream in birdhouse. 
https://github.com/bird-house/flyingpigeon/issues/231

**Comment by bstdenis** [comment]
Available in PAVICS-DataCatalog 0.6.3
