### ISSUE TITLE
Upload river network

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#3]
Add river network to geoserver so it can be shown on the map.

**Comment by Zeitsperre** [comment]
I'll be working on this. Is there a permissions schema needed for you to access it?

**Comment by Zeitsperre** [comment]
National Hydro Network polygons are up. nhn_rhn_02SA and nhn_rhn_02SA. In the scratchTJS workspace. Is this what you had in mind?

**Comment by huard** [comment]
More or less. I was looking for a high-level province or canada wide layer of the major rivers. The files that you added cover two watersheds and go in very small detail. 
Also, the river network shows up in dark gray, which is barely visible on the satellite basemap. Is it possible to configure the river network to be displayed in flashy blue ?

**Comment by Zeitsperre** [comment]
Ah, I wasn't sure of the scale you had in mind. I have the data set in mind and can set an appropriate style.

**Comment by huard** [comment]
Indeed, my request was not very precise. While you're at it, could you note the steps that you go through to do this and add them to the docs. See docs/source/dev/geoserver.rst

**Comment by Zeitsperre** [comment]
Already on it. Need to learn the Markdown style but it's en route.

**Comment by Zeitsperre** [comment]
Canvec Rivers and CanVec Water bodies are selectable and styled. Adding documentation now.
