### ISSUE TITLE
Mechanism to inform UI of map interaction

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#31]
At the moment the UI relies on process input identifiers to determine its behavior. For example, it knows the process requires a map interaction if (typename, featureid) are found in the input parameters, so if an input's name matches some pattern, clicking on the map will feed information into the form. 

I suggest we find a more robust way to tell the UI an input requires a map interaction. This will likely require a refactoring of the processes, but I think it's worth it. One possibility is to replace the two typename and featureid fields by one "polygon" field, with mimetype "application/xml+gml". When the user selects a region from the UI, the input is fed the GML description of the polygon obtained from geoserver (or the URL, not clear to me yet). 

This would allow us to implement other type of map interaction such as a bounding box selector, and use the same mechanism.

**Comment by huard** [comment]
David, Francis, I'd like to have your thoughts on this. I could create a dummy process in emu to make testing easier.

**Comment by dbyrns** [comment]
A lot of stuff about this topic is available here : https://www.crim.ca/confluence/pages/viewpage.action?pageId=21759389

What I understand from that is that we would need a button or something beside each input field that would allow selecting one or more parameters from one or more sources. 
e.g. Datasets could come from the layer switcher (as current) but also from workspace or from search.
       Shapefiles could come from layer switcher (as current) but we are thinking about allowing adding them to the workspace too and even taking them from geoserver?

So I think that a major refactoring has to be done, but some design must occur before that.

**Comment by huard** [comment]
Yes, so my suggestion would be to replace "Supporter des sous-ensembles du type string ..." by "Supporter des ComplexInput en fonction de leur mimetype", with 

- application/x-netcdf
- application/xml+gml

as the main two targets. I haven't thought much about how the interface would have to be redesigned, but I assume you're right, an input with a given mimetype could trigger the creation of custom buttons, including your suggestions (workspace, geoserver, UI, boundingbox widget). 

Agreed. I suggest that we organize a brainstorming session this Fall with UI developers, backend people and users to clarify all this.
