### ISSUE TITLE
Login as another user?

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#33]
I've noticed something else strange today, specific to pavics.ouranos.ca.

Logging in using my credentials for the server/geoserver consistently fails:
![screenshot from 2018-04-03 11-19-57](https://user-images.githubusercontent.com/10819524/38258788-5f471dbc-3731-11e8-934a-21e3fc04f592.png)

However, waiting 2-3 minutes after a failed login attempt, I am automatically signed in as @moulab88:
![screenshot from 2018-04-03 11-20-56](https://user-images.githubusercontent.com/10819524/38258826-7ad42a34-3731-11e8-92fb-73a2698889e7.png)

Is this normal behaviour?

**Comment by Zeitsperre** [comment]
Developments: I think this might be based on IP address as when I logged in this morning I saw that I was now David: 
![screenshot from 2018-04-04 09-41-54](https://user-images.githubusercontent.com/10819524/38311323-e7de17a0-37ec-11e8-80f3-6cf640e4d1ac.png)

@huard, do you tunnel in with VPN? It could be that the system sees all ouranos.ca addresses as the same users.

**Comment by huard** [comment]
Correct, I use the VPN to access the platform.

**Comment by dbyrns** [comment]
@Zvax I need to talk about that with you since it can be related to the PAVICS frontend or Magpie or both.
Have you guys been able to reproduce that using only Magpie UI? Or is it only occuring on the PAVICS UI?

**Comment by Zvax** [comment]
It's strange that ouranos.ca would treat all logins as the same, I don't think we've experienced a similar session boundary bleeding even though we all access the platform from the same place.

I observe that the /login request to magpie returns multiple auth_tkt cookies, for different domains. I'm not quite sure at this time what that entails, but it seems to glitch with the logout, as only one of the multiple cookies are deleted.

We confirmed with @dbyrns that it's possible for an auto login to happen when the cookie is still present in your browser. In this scenario: someone logs on to the platform, goes away without using logout, someone else uses their computer to access the platform, the still present cookie will be considered as an active session.

**Comment by Zeitsperre** [comment]
@Zvax I'm not sure. I just checked out the platform and saw I was logged onto the Ouranos deployment as @moulab88 just now. Is there a method of checking my local files to see if the credentials are saved in my browser?

**Comment by Zvax** [comment]
Depending on your browser you could look in the preferences to see if there are saved credentials for the pavics domain, but that should not matter in theory. I have not created automated submission of the form.

On page load, the platform checks to see if there is a token present in the cookies. If there is, a call to /session is made, that will log the stored user if a session is active.

**Comment by dbyrns** [comment]
Ok I saw that happens on Magpie too... I logged on pavics.ouranos.ca/magpie from firefox and after refreshing the page pavics.ouranos.ca/magpie on chrome I was suddently logged in. magpie api /session return a valid auth_tkt. So this is mainly a Magpie issue.

**Comment by dbyrns** [comment]
That was my previous assumption but if you read my post carefully you will notice that I was not logged in chrome, log from firefox, then a simple refresh on chrome was enough to log me in. I doubt that cookies are shared between firefox and chrome 😁. I don't know how but /session seems to return a auth_tkt from cache... maybe a nginx cache issue? I dont know.

**Comment by dbyrns** [comment]
@ldperron I think you are in a good position to help us on this. Latest observation : The "auto-login" do not occurs every time, so it could be hard to reproduce. The ouranos server failed pretty often and show the following error after probably having timed out : 
"An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the error log for details.
Faithfully yours, nginx."

**Comment by dbyrns** [comment]
/signout should also be investigated because the cookie doesn't seem to be invalidated.
And while working on that an expiration should also be considered.

**Comment by Zvax** [comment]
My observations so far:

/signin generates a new cookie names auth_tkt each time it is called
/session returns a valid login when presented with any of the cookies that have been generated from /signin
/signout does not invalidate a cookie: it seems that even after calling /signout with a cookie, manually reusing it to call /session will return valid authorisation

**Comment by huard** [comment]
Note that if the cookie name changes, wps_pavicrawler needs to be adapted because auth_tkt is hard-coded.

**Comment by Zvax** [comment]
@huard The name need not be changed _for now_, I just don't know why there are three of them.

When we want to support openid and esgf (both of these using differently named cookies that need to be dynamic) we'll have to stop relying on hardcoding auth_tkt everywhere.

**Comment by fmigneault** [comment]
@Zvax 
There is no duplication of the code.
The thing is that in this repo, both the API and the UI are implemented.

The 1st link you provided is the API, the 2nd the UI.
For logging in/out, or any other operation that is, the UI calls the corresponding API routes, with some extra checks for display purposes.

**Comment by ldperron** [comment]
After tests with curl, the REST call to /session currently always gives me "cypress" as logged in user, regardless of the value of auth_tkt, while calls to /magpie/session performs the appropriate behavior. Currently digging further

**Comment by ldperron** [comment]
koa-proxy clearly remember the cookies... They are gone when I restart frontend, but as soon as someone logins through the platform, it's back.

**Comment by ldperron** [comment]
Fix is here: https://github.com/Ouranosinc/PAVICS-frontend/pull/95

Note: the logout from the platform is not working properly. This will be covered in https://github.com/Ouranosinc/Magpie/issues/29

**Comment by ldperron** [comment]
Deployed on *.crim.ca
