### ISSUE TITLE
Update flaky WMS notebook example nearing deprecation

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/pavics-sdi#332]
As flagged in https://github.com/bird-house/birdhouse-deploy/pull/466#issuecomment-2341732161, the sample WMS notebook https://github.com/Ouranosinc/pavics-sdi/blob/master/docs/source/notebooks/WMS_example.ipynb often fails. The server either responds (or fails to respond?) with a valid XML, which causes the OWSLib WMS tool to fail parsing the contents. This causes https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests to often fail the https://github.com/bird-house/birdhouse-deploy CI, leading to a maintenance overhead when working on other features.

After looking up the referenced server, I landed on the following alert: 
https://neo.gsfc.nasa.gov/blog/2024/08/30/neo-wms-web-mapping-service-deprecation-alert/
> August 30th, 2024 by Kevin Ward
> 
> At some point in late 2024/early 2025 we will be decommissioning the [NEO Web Mapping Service](https://neo.gsfc.nasa.gov/about/wms.php) (WMS). [...]

It seems to be a matter of time until the sporadic failures become a constant failure. 
An updated WMS example should be provided to employ a more reliable server. 
The current WMS example could be left for documentation purpose, but might need to be disabled...

**Comment by huard** [comment]
I'm happy to pull it from our docs. It's nice, but semi-useful from a data analysis perspective.
