### ISSUE TITLE
Populating climate data on Boreas

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#36]
In the past day, I've transferred over the following datasets:

- CORDEX: AWIx, CCCMAx, DMIx, MGOx, MOHCx, SMHIx, ULgx, UQAMx
- NCEP: NARR, Reanalysis2

And currently transferring over:

- CMIP5: CCCMA

Once the last one is in, I'll see about running the crawler to update data.

**Comment by huard** [comment]
Do we have observational data sets ? Those can be restricted access if we're not sure about permissions to distribute.

**Comment by Zeitsperre** [comment]
There is current a set of NRCan daily pr, tasmin, tasmax data from 1950-2013 on Boreas. I'm unsure if this is already the case, but this data set should be limited to internal users as it isn't public. If we want to add more, I can look into recuperating HadCRU data (also not open to public).

**Comment by huard** [comment]
Good, I'm just not seeing it when searching through the data. Is it crawled correctly ? Does it have a "project" name ?
No, let's stick to this for the moment. We'll add datasets later when more pressing issues have been fixed.

**Comment by Zeitsperre** [comment]
I'm not seeing any data available in the search, which is worrisome. As soon as the CMIP5 data is in, is running the crawler as simple as loading the following?
http://<servername>:8009/pywps?service=WPS&request=execute&version=1.0.0&identifier=pavicrawler&storeExecuteResponse=true&status=true&DataInputs=

**Comment by huard** [comment]
Euh, good question. I had hoped Blaise would have had told you that before
he left.

**Comment by Zeitsperre** [comment]
ncdump is not available on Boreas, but if the data is the same as what was converted to netcdf on /scen2, there isn't a "project" name. The only metadata I can find are "Title", "History", "Institution", " Source", and "Redistribution".

**Comment by Zeitsperre** [comment]
I believe that is the method of running the crawler. I've only done it a few times though. I'll test it out as soon as the data transfer is complete.

**Comment by huard** [comment]
Ok, let's try it. 
I'll create a ticket to review metadata.

**Comment by Zeitsperre** [comment]
Running pavicrawler now.
