### ISSUE TITLE
Review metadata of files on THREDDS server

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#37]
Some datasets do not have the project facet and may not be fully compliant with CF conventions. 
I think this will cause problem down the line. 
I suggest we scan files on the THREDDS server using https://github.com/ioos/compliance-checker, report issues found and start cleaning meta-data when it can be easily done. For more complex problems, I suggest removing the files from THREDDS. 

The checks would ideally cover both the netCDF metadata and the file name (see [pyessv](https://github.com/ES-DOC/pyessv))

-[ ] Select scanner library
-[ ] Create process to scan the library and report the issues in an HTML document 
-[ ] Automate the process and host the HTML output
-[ ] Put in place scripts that help with meta-data modifications and keep a trace of what was done.

**Comment by huard** [comment]
@Zeitsperre What could be a realistic time frame to do this ?

**Comment by Zeitsperre** [comment]
I'll start looking into this Monday and let you know.  Do you simply want me to run it over the files and remove fix individual files or do you want me to try building a process or of it?

**Comment by huard** [comment]
The former for now, but please discuss with CRIM how to integrate these checks into standard platform operations, similar to what we do with travis and coverage. Should the crawler for example report on non-compliance ? How is this exposed to the admin ?

**Comment by Zeitsperre** [comment]
I should be at CRIM next Tuesday. I'll speak with the group about this then.

**Comment by huard** [comment]
@tlvu this is something you could work on.

**Comment by tomLandry** [comment]
For CCDP. I think we actually need those kind of check for everything coming out of Finch, as well as for the BCCAQv2.

**Comment by tomLandry** [comment]
@huard can you keep Ryan Smith from PCC in the loop? His team will provide some QA on the computed climate indices. I'm curious to see how much of this could be automated. See for reference here, in the comments: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/11731007/Datasets

**Comment by huard** [comment]
The two issues have partial overlap. We are planning to automatically QA the CF compliance only, not the actual data content.

**Comment by tomLandry** [comment]
An idea, maybe anomalies like these ones could be detected: https://bit.ly/2SvwhTJ

**Comment by huard** [comment]
See #112 and ncISO. Maybe this meets our needs. 
See for example: https://thredds.cdip.ucsd.edu/thredds/uddc/cdip/realtime/226p1_rt.nc?catalog=https%3A%2F%2Fthredds.cdip.ucsd.edu%2Fthredds%2Fcatalog%2Fcdip%2Frealtime%2Fcatalog.html&dataset=CDIP_Realtime%2F226p1_rt.nc

**Comment by huard** [comment]
Public datasets via clean NcML views.
