### ISSUE TITLE
Server deployment issues should not be publicly accessible

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#38]
Something that came up in a discussion between me and @dbyrns was that many of the questions/issues on here that reference servers and deployment criteria are viewable to the general public. This isn't a great security practice.

As it stands, we have a few issues (e.g. #1, #34, #35) where specific servers at Ouranos or CRIM are identified. Would it be better to discuss the deployment/server issues that arise on the issues the protected "PAVICS" repo?

In the meantime, I've looked the possibility of migrating issues to another repo and GitHub explicitly does not allow this natively. Ways of doing this (e.g. [a Google-made tool](https://github.com/google/github-issue-mover) and a [Chrome Extension](https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf?hl=en-US)) introduce graver security concerns, so we may need to migrate the issues manually if we choose to do this.

Thoughts?

**Comment by huard** [comment]
Agreed. I'll migrate those issues manually to PAVICS.

**Comment by Zeitsperre** [comment]
Sounds good to me. @dbyrns?
