### ISSUE TITLE
Technological and scientific outreach 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#39]
See EarthCube projects: https://www.earthcube.org/groups

I suggest we identify and connect with projects that are relevant to our activities.

**Comment by tlogan2000** [comment]
Ok I will take a look.  

Browsing quickly there are some with obvious links (e.g. PANGEO : https://pangeo-data.github.io/) 

But are we aiming for people building similar platforms to DACCS / PAVICS (like the above example) or potential users?
