### ISSUE TITLE
Item scroll arrows show negative-indexed files

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#44]
Found this just now:
![screenshot from 2018-05-07 14-02-34](https://user-images.githubusercontent.com/10819524/39717212-8e3a1f72-5200-11e8-83c1-85d7cb446f74.png)
![screenshot from 2018-05-07 13-43-49](https://user-images.githubusercontent.com/10819524/39717217-90295a78-5200-11e8-84c2-8e0a9e63a2f3.png)

The selection arrows can (try) to show files that are negatively indexed in a results list. This seems to be universal across the platform UI.

**Comment by Renaud009** [comment]
Arrows are normally disabled, we could add a second validation to prevent event triggering.
What browser/OS was used?

**Comment by Zeitsperre** [comment]
This was with Chromium. I'll try reproducing with Firefox.

**Comment by Zeitsperre** [comment]
Seems to only be the case with Chromium. I imagine Chrome would have the same behaviour?

**Comment by Renaud009** [comment]
Somehow happening on chrome too now, easy to fix.

**Comment by Zeitsperre** [comment]
@Renaud009 The fix for this has been integrated, right? I can't reproduce this anymore. Move to verify?
