### ISSUE TITLE
Shapefile and region name with accented character may be problematic when launching a WPS/Workflow from the platform

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/pavics-sdi#46]
Looks like Phoenix or some other part of the infrastructure fail at encoding these chracters in ASCII

![image](https://user-images.githubusercontent.com/14914217/39767945-ef74719c-52b5-11e8-9a5f-b92f0aae2641.png)

**Comment by Zeitsperre** [comment]
I'm currently fixing topologies and field types for sdhapefiles. If this isn't an easy fix, I can try scrubbing accented strings in shapefiles prior to loading.

**Comment by Zeitsperre** [comment]
I've looked at the possibility of converting accents in names to base characters (ie: 'É to 'E') and for shapefile entries/objects there is no good method for doing it. For shapefiles not made in Quebec this is fine, but for MRC and Municipal Regions, not so much.

@Renaud009 would it be adequate to simply rename the shapefile titles to remove accents or do the names of entries within shapefiles need to be renamed as well? I ask since, for instance, if someone were to do a region subset with the polygon for "Monérégie", would the request demand the object by name (ie: '?shapefile=mrc_regions&object=montérégie') or would it use the the FID (ie: '?shapefile=mrc_regions&fid=101').

**Comment by dbyrns** [comment]
For the demo at least we should remove accents on what we intend to use

**Comment by Zeitsperre** [comment]
As it stands, the shape names for vectors in GeoPackage no longer have accents. So long as feature names aren't selected via a row entry containing accents (e.g. "fr_name"), there should be no problem. I'll go ahead and upload the new shapes today to outarde and close this issue.

**Comment by dbyrns** [comment]
I asked Mario if the data_dir of geoserver could be copied over the other birds once outarde is ready and it looks like it could be done. So the host path /data/geoserver could be copied over since it supposedly contain data and catalog info.

**Comment by Zeitsperre** [comment]
Nice. I'll let you know once that's completed. Would this also preserve SLD styles set for layer entries? That would cure a lot of headaches.

**Comment by dbyrns** [comment]
Ok @Renaud009 reports me that outarde's geoserver instance seems broken. 
I would like to remind everybody (@Zeitsperre, @tlogan2000, @huard, CRIM people already know) that outarde is a "prod" server and tests should be done on pluvier or colibri. If the tests are concluding then we can proceed with hirondelle on which tests are run by jenkins. If everything still works then we can go on with outarde and boreas.

**Comment by dbyrns** [comment]
@Zeitsperre once the copy is done on a dev server I will let you know so you can check if everything is ok. Then we will proceed with the other hosts.

**Comment by Zeitsperre** [comment]
@dbyrns Noted. Sorry about that! I'll perform future tests on Colibri/Pluvier!

**Comment by Zeitsperre** [comment]
This should now be dealt with. https://github.com/Ouranosinc/PAVICS/issues/64

**Comment by Zvax** [comment]
@Zeitsperre it seems the frontend is unbale to fetch any shapefiles as of now on Outarde. They're normally returned in the getCapabilities.

**Comment by Zeitsperre** [comment]
That's really strange. It was working just before. I'll try disabling that layer and see if it brings them back.

**Comment by Renaud009** [comment]
@Zeitsperre This issue could be closed when all space caracters are removed from boreas polygons since this could open a new set of errors with flyingpidgeon.

**Comment by Zeitsperre** [comment]
@Renaud009 Sure thing. I can fix that issue later today. Maybe down the line, we can look into ways of setting a title with spaces but performing calls on a space-free version of the file (ie: title vs filename in GeoServer). I'll look into this functionality at the same time.
