### ISSUE TITLE
GeoServer should be updated to 2.13+

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#47]
Seeing as the version of GeoServer bundled in PAVICS (v2.9) is around 2.5 years old, it would be good to update it to a more recent iteration.

Some of the improvements over the past 2.5 years include better performance for reading/writing/displaying shapefiles, postgreSQL/postGIS geometries, NetCDFs as well as better management and UI. @tlogan2000  and I suggest updating to at least 2.13+, as read/write/display performance for GeoPackages (a newer/better OGC standard than shapefiles/gml) is on par with SQL databases.

**Comment by tomLandry** [comment]
We've tried the NetCDF plugin for GeoServer at one point, maybe a year ago or so. Offers a WCS/WMS interface that could possibly replace or complement NcWMS/THREDDS at full scale. But we haven't gone very far as this broke apart pretty quicky for large files.

**Comment by tlogan** [comment]
@Zeitsperre I'm guessing you meant a different tlogan.  I'm not familiar with this project.

**Comment by Zeitsperre** [comment]
Yeah, I meant I meant @tlogan2000. Sorry!

**Comment by Zeitsperre** [comment]
@tomLandry The benefits would more be for serving vector data more effectively/efficiently and for making it much easier to manage (ie: better SLD support, GeoPackage standard support, other improvements since 2.9). I'm not suggesting this replace NcWMS, I'm more interested in us making use of better file standards if that makes sense.

**Comment by Zeitsperre** [comment]
This is now being addressed in https://github.com/Ouranosinc/PAVICS/pull/90
