### ISSUE TITLE
Mismatch between search criteria and data shown

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#48]
To reproduce on pavics.ouranos.ca
Search Datasets
- Project: ClimEx
- Frequency: day
- Variable: tas

First weird thing is that the Variable drop down menu now displays: poids, tasmax and tasmin. It's not clear why these variables would show up. There are 10 results, whose name suggest they store tasmin and tasmax. I would be expecting `tas` only. 

For all of these datasets, the interface displays: 
`Variable: valeur des poids utilises pour faire la statistique`

Selecting a dataset and "Add selection" raises an error. (Failed to fetch).

If I then select `tasmax` in addition to `tas`, the dashboard says `Found 8700 total files in 5 results` but displays no search result. 

If I click on X to remove tasmax, the dropdown menus for all the search facets die.

**Comment by Renaud009** [comment]
So there a couple things to investigate here:
1- search return facets that shouldn't be returned: https://github.com/Ouranosinc/PAVICS-frontend/issues/65
2- I noticed too a week ago that on borea 'height' was now 'poids' (!?)
3- Frontend shows only first variable returned in variables 'array' which is 'poids'
4- project-api returns in fact POST https://pavics.ouranos.ca/project-api/api/Projects/13/datasets 413 (Request Entity Too Large) which is weird. Could be a limitation of the nodejs server and/or nginx. If the datasets contains 1740 files, JSON object might big indeed

**Comment by ldperron** [comment]
@Renaud009  Can you give me the exact URL that triggered the 413 Too Large error? It's most likely a configuration issue with nginx, since the default is 1MB.

**Comment by Renaud009** [comment]
The URL I provided on Step 4 with a relatively big json body. Manipulating any dataset (PUT, POST, GET) on boreas containing 1700+ files will trigger such error.

**Comment by ldperron** [comment]
Corrected by hand on Boreas.

**Comment by ldperron** [comment]
project-api config (fixes 413 Payload Too Large): https://github.com/Ouranosinc/PAVICS-project-api/commit/c1af88a91dfe68750f82376de9d3df5a20ce5144
