### ISSUE TITLE
Cannot access xml status of flyingpigeon

### ISSUE THREAD

**Issue by dbyrns** [Ouranosinc/pavics-sdi#50]
If I run the following request : 
https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps?service=WPS&request=execute&version=1.0.0&identifier=subset_WFS&storeExecuteResponse=true&DataInputs=resource=https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/fileServer/birdhouse/CCCMA/CanCM4/historical/mon/atmos/r9i1p1/pr/pr_Amon_CanCM4_historical_r9i1p1_196101-200512.nc;typename=usa:states;featureids=usa_admin_boundaries:1;mosaic=True

And try to open the xml status link, like this one : https://pavics.ouranos.ca/wpsoutputs/flyingpigeon/bef66456-5532-11e8-a6aa-0242ac12000c.xml

I got a 404

**Comment by ldperron** [comment]
I think it's because the request fails too soon (during input validation maybe).
>Process error: wps_subset_WFS.py._handler Line 79 Traceback (most recent call last): File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/processes/wps_subset_WFS.py", line 76, in _handler result = wfs_common(request, response, mode='subsetter') File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/handler_common.py", line 76, in wfs_common raise Exception(msg) Exception: Failed to fetch features. geoserver: http://pavics.ouranos.ca:8087/geoserver/wfs typename: usa:states features [u'usa_admin_boundaries:1'] Unknown namespace [usa]

Indeed, usa:states doesn't exists on Boreas.
It's: scratchTJS:usa_admin_boundaries

**Comment by dbyrns** [comment]
It will not help workflows if they cannot get the process failed status... 
Then I will replace this issue in the backlog and see how we can improve flyingpigeon later so that the exception is properly catched and report as it should.

**Comment by huard** [comment]
@ Toujours un enjeu ? Si oui ouvrir un ticket sur PyWPS.

**Comment by dbyrns** [comment]
Je vais faire le suivi.
