### ISSUE TITLE
Create terms of use / permissions mechanism for data sets hosted on PAVICS 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#51]
Users need to be made aware (and accept) permissions / credits / terms of use for the various datasets on the platform. 

Permissions/access to individual datasets can be managed in Magpie, however even some 'public' datasets can have conditions of use (e.g. need to acknowledge/cite in any publications, not for profit use only etc.)

Need to create a mechanism for users to consult and agree to these types of conditions for the ensemble of data on the platform. 

Also need to establish an official / standard way to update this each time a new dataset is added

**Comment by Zeitsperre** [comment]
AT the very least, the vector data that we currently have is either within the public domain or (at worst) under a CC-BY license. Satisfying these terms is as simple as adding an attribution to the webmap ([like so](https://www.tutorialspoint.com/leafletjs/images/attribution_map.jpg)).

Although we are technically operating as a not-for-profit, one issue that I can see with password protected content is that the Bing basemaps TOU starts getting more restrictive for us as we start implementing more usage protections on our end ([TOU](https://www.microsoft.com/en-us/maps/product)). An excerpt:

> "Education or Non-Profit Organization Use" means using the Services with a Company Application that displays results for education or non-profit use, where non-profit organization means a tax exempt organization and education means use by public or private K-12 schools, universities, community colleges or other collegiate level institutions such as vocational schools, trade schools or career colleges, including their faculty, staff, and students, provided that your use is consistent with the terms of Section 5. Further your Company Application must be one of the following: publicly available without restriction (for example, login or password must not be required), available only to current students of your education organization via your private network in order to provide education related services, available internally for free instructional use, or available internally for non-commercial research use. Commercially funded research projects and commercial company use for educational purposes are excluded from Education or Non-Profit Organization Use.  

If this is a serious issue, it could probably be dealt with technically by either by paying for pseudo-commerical use of services like Bing and/or MapBox, using the OpenStreetMap basemap, or generating the tiles ourselves (using ArcGIS/QGIS or MapBox). Some clarity on this would be good.

**Comment by Zeitsperre** [comment]
Updates on this. See: https://github.com/Ouranosinc/PAVICS/pull/90/commits/d3d5b8d95f37b988e9ab83f2def530f2a64d9210

**Comment by huard** [comment]
@Zeitsperre @tlogan2000 
Is this solved by the NcML strategy ?

**Comment by tlogan2000** [comment]
I think the NcML allow us to add licence info but we still need a mechanism to communicate use of the platform (pavics) as a whole when users go on the jupyter hub, as well as say something along the lines of  "by accessing the platform and associated data you agree to respect data licence information available in the dataset metadata etc etc..."

I think a check box plugin like this could be useful ... but still need to create appropriate legal wording of the terms 

https://github.com/ResearchComputing/jupyterhub-options-spawner

**Comment by huard** [comment]
Can we just have a Terms and conditions text file along the README ? 
Who will write those ?

**Comment by tlogan2000** [comment]
I think @Zeitsperre is the most capable with help from Agnes to write something ... In each user workspace could then have a terms&condtions notebook or file along with the tutorial examples.  The check box extension could then have something simple like I agree to terms outline in the 'terms&conds' notebook?

**Comment by huard** [comment]
Sounds good.

**Comment by Zeitsperre** [comment]
Agnès and I are certainly working towards this. We spoke briefly today and are aiming to have a few mechanisms in place to deal with external and internal (e.g. MRCC5) data sets. I'm currently working on a few things with regards to CCDP data today but expect updates on recommendations for more data sets by end of next week.

**Comment by huard** [comment]
@tlogan2000 Can this be closed ?

**Comment by dbyrns** [comment]
We have an open issue to handle this issue specifically in DACCS : [https://www.crim.ca/jira/browse/DAC-119].
All prerequisites work in Magpie has been done, we should be able to implement this in the short term.

**Comment by tlogan2000** [comment]
> @tlogan2000 Can this be closed ?

Fine to close on my end
