### ISSUE TITLE
NCWMS2 GetCapabilities returns java.lang.IllegalArgumentException: Coordinate values must increase or decrease monotonically

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/pavics-sdi#55]
NCWMS2 retourne ces erreurs pour plusieurs datasets présents sur les oiseaux:
java.lang.IllegalArgumentException: Coordinate values must increase or decrease monotonically
	uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.checkAscending(AbstractIrregularAxis.java:113)
	uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.init(AbstractIrregularAxis.java:102)
	uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.&lt;init&gt;(AbstractIrregularAxis.java:63)
	uk.ac.rdg.resc.edal.grid.TimeAxisImpl.&lt;init&gt;(TimeAxisImpl.java:51)
	uk.ac.rdg.resc.edal.util.cdm.CdmUtils.createTimeAxis(CdmUtils.java:296)
	uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.createDataset(CdmGridDatasetFactory.java:213)
	uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.createDataset(CdmGridDatasetFactory.java:82)
	uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.getDatasetFromId(NcwmsCatalogue.java:170)
	uk.ac.rdg.resc.edal.wms.WmsServlet.getCapabilities(WmsServlet.java:538)
	uk.ac.rdg.resc.edal.wms.WmsServlet.dispatchWmsRequest(WmsServlet.java:311)
	uk.ac.rdg.resc.edal.ncwms.NcwmsServlet.dispatchWmsRequest(NcwmsServlet.java:176)
	uk.ac.rdg.resc.edal.wms.WmsServlet.doGet(WmsServlet.java:245)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

Exemples:
https://outarde.crim.ca/twitcher/ows/proxy/ncWMS2/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&DATASET=outputs/CMIP5/CCCMA/CanESM2/historical/day/atmos/r1i1p1/tasmax/tasmax_day_CanESM2_historical_r1i1p1_19790101-20051231.nc

https://outarde.crim.ca/twitcher/ows/proxy/ncWMS2/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&DATASET=outputs/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/pr/pr_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc

**Comment by tomLandry** [comment]
@cehbrecht : I think we had this error in the past and Blaise (not with us anymore) solved it. I vaguely recall this to be linked to broken data. Seen that before?

**Comment by tomLandry** [comment]
/**
     * Checks that the axis values ascend or descend
     * monotonically, throwing an IllegalArgumentException if not.
     */
    private void checkAscending()
    {
        double prevVal = axisValues[0];
        for (int i = 1; i < this.axisValues.length; i++)
        {
            if (this.axisValues[i] <= prevVal)
            {
                throw new IllegalArgumentException("Coordinate values must increase or decrease monotonically");
            }
            prevVal = this.axisValues[i];
        }
    }

**Comment by tomLandry** [comment]
Good read on GitHub on this very problem right here: https://github.com/Reading-eScience-Centre/edal-java/issues/26

**Comment by tomLandry** [comment]
guygriffiths, 14 sept 2015: "Fixed in develop branch. EDAL was ordering the files by the values of their time axes, but was reading the time values as longs. When these were all on the same day, no reordering was applied. Fixed by reading time values as floats." 

[NcWMS is now at 2.4.1](https://github.com/Reading-eScience-Centre/ncwms/blob/master/CHANGELOG) and we're at 2.0.4. I suggest a version upgrade on one of the smaller birds. @dbyrns how difficult would that be?

**Comment by dbyrns** [comment]
Near impossible... @fmigneault  try to rebuild a docker image in the past and failed. We could try it again but I highly doubt that we could achieve this for the demo.

**Comment by Zeitsperre** [comment]
As was mentioned in the standup meeting, for reference, the 'values not monotonically increasing' error will happen if any Dimensions in a NetCDF that are float values are not read with enough precision (ie: -179.1, -179.0, -178.9 is good; -179, -179, -178 is bad).

**Comment by tomLandry** [comment]
Then @Zeitsperre we have to massage the data so NcWMS won't complain it seems.

**Comment by cehbrecht** [comment]
I haven't looked at NcWMS for quite a while. I can update the conda package and the Dockerfile in birdhouse. But if you only need the docker image maybe there is a better maintained one available on dockerhub.

**Comment by cehbrecht** [comment]
In the long run I would prefer to use "officially" maintained docker images. But, yes, configuration can be an issue ... this is probably different for each maintainer.

I will look in updating ncwms in birdhouse (conda, docker). You can choose which one works best for you :)

**Comment by dbyrns** [comment]
I'm looking into what should be done with the official image so that data are fetch and serve like the old one. It may be pretty easy...

**Comment by tomLandry** [comment]
@Zeitsperre : maintainer from NcWMS is ready to help. He would need our seemingly broken data to reproduce. Maybe an OpenDAP link or THREDDS?

**Comment by tomLandry** [comment]
Following our discussion, here is the file from our [OPEnDAP server](http://outarde.crim.ca:8083/thredds/catalog/birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/catalog.html?dataset=birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc)

Catalog http://outarde.crim.ca:8083/thredds/catalog/birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/catalog.html
Dataset: tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc
Data size: 1.137 Gbytes
ID: birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc
Access:
HTTPServer: /twitcher/ows/proxy/thredds/fileServer/birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc
OPENDAP: /twitcher/ows/proxy/thredds/dodsC/birdhouse/CMIP5/CCCMA/CanESM2/rcp85/day/atmos/r1i1p1/tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc
Dates:
2018-05-08T19:25:50Z (modified)
Viewers:
NetCDF-Java ToolsUI (webstart)

**Comment by Zeitsperre** [comment]
Just copied over that exact file from crim-internal server. Visualizing it raises no errors.
![tasmax_canesm2_rcp85_r1i1p1_daily](https://user-images.githubusercontent.com/10819524/40069084-48188bda-5838-11e8-9999-07491e026991.png)

**Comment by cehbrecht** [comment]
There is an attempt of community maintained docker images:
http://geocontainers.org/

But looks outdated ...

**Comment by dbyrns** [comment]
I look at the latest ncwms2 image : https://hub.docker.com/r/guygriffiths/ncwms/
And I think that all we have to do is mount the following files into it : 
https://github.com/bird-house/birdhousebuilder.recipe.ncwms/blob/master/birdhousebuilder/recipe/ncwms/config.xml to
/usr/local/tomcat/.ncWMS2/config.xml

https://github.com/bird-house/birdhousebuilder.recipe.ncwms/blob/master/birdhousebuilder/recipe/ncwms/ncWMS2.xml to /usr/local/tomcat/conf/Catalina/localhost/ncWMS.xml

https://github.com/Ouranosinc/PAVICS/blob/master/birdhouse/config/ncwms2/server.xml to /usr/local/tomcat/conf/server.xml

Template values for PAVICS are almost all the default ones specify here : https://github.com/bird-house/birdhousebuilder.recipe.ncwms
We only override the ncwms_password and the data_dir
data_dir have been replaced in the template by dynamic-services and should look like this : 
"dynamic-services = outputs=/pavics-data"

**Comment by cehbrecht** [comment]
I tried to update the ncwms image using the buildout:
https://hub.docker.com/r/birdhouse/ncwms2/

But it is still not working :( 

If you can use the docker image by guygriffiths it would be the better choice.

My ncwms Dockerfile is living here:
https://github.com/bird-house/birdhouse-docker-images/tree/master/ncwms2

Would be nice to have community maintained images for those services we just use and configure:
https://github.com/bird-house/birdhouse-docker-images/issues/1

**Comment by Zeitsperre** [comment]
@Zvax That doesn't look right at all. I just downloaded and checked the 'time' and I can see the error on my end as well. Looking at ncdump, it seems as though this came directly from CCCMA and history shows nothing notable, so I have no idea how/when the time dimension got corrupted. I say disregard this file and I'll add a new/different version.

**Comment by Zvax** [comment]
I verified the other dataset, tasmax/tasmax_day_CanESM2_rcp85_r1i1p1_20060101-21001231.nc, (mentioned by @tomLandry) as well, and there is that same thing where the time dimension have a stripe of strange values in the middle:

```
    54476.5, 54477.5, 54478.5, 54479.5, 54480.5, 54481.5, 54482.5, 54483.5, 
    54484.5, 54485.5, 54486.5, 54487.5, 54488.5, 54489.5, 54490.5, 54491.5, 
    54492.5, 54493.5, 54494.5, 54495.5, 54496.5, 54497.5, 54498.5, 54499.5, 
    54500.5, 54501.5, 54502.5, 54503.5, 3.99806390033924e-47, 
    2.88969763368863e-38, 3.61181940230661e-35, 1.16677822260747e-33, 
    4.80531465108474e-37, 3.83547555141028e-44, 1.66790546265913e-34, 
    1.16026731006209e-34, 5.70793526006812e-35, 8.45809382859479e-37, 
```

**Comment by ldperron** [comment]
I'm replacing all CCCMA files on Outarde. Almost all of them has corruption.

**Comment by ldperron** [comment]
CCCMA done on Outarde, hirondelle and pluvier.

**Comment by ldperron** [comment]
And colibri

**Comment by Zeitsperre** [comment]
@huard AFAIK, no problems to be found with the CMIP5 data at Ouranos. Not sure how this corruption happened. Should I copy over another experiment?

**Comment by huard** [comment]
No, let's focus on the demo.

Are you able to browse the geoserver shapefiles from QGIS ?

**Comment by Zeitsperre** [comment]
![screenshot from 2018-05-17 16-31-08](https://user-images.githubusercontent.com/10819524/40202371-c0bc48e8-59ef-11e8-844e-41dafb235067.png)

**Comment by tomLandry** [comment]
@dbyrns, can we close this? I get from comments that this problem is solved, at least on our end.
