### ISSUE TITLE
Flying pigeon returns IOError: File too large to download

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/pavics-sdi#57]
Dans un workflow très simple Une tâche de subsetting retourne 
`Process error: wps_subset_WFS.py._handler Line 79 Traceback (most recent call last): File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/processes/wps_subset_WFS.py", line 76, in _handler result = wfs_common(request, response, mode='subsetter') File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/handler_common.py", line 46, in wfs_common raise Exception(traceback.format_exc()) Exception: Traceback (most recent call last): File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/handler_common.py", line 44, in wfs_common output_path='/tmp') File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/utils.py", line 1217, in opendap_or_download raise IOError("File too large to download.") IOError: File too large to download.`

Résulat: https://outarde.crim.ca/wpsoutputs/flyingpigeon/e175dacc-57b5-11e8-ba68-0242ac120007.xml
Workflow: 
```
{
	"name": "parsingcatalog_parallel_subset",
	"tasks": [
		{
			"name": "ParsingCatalog",
			"provider": "malleefowl",
			"url": "https://colibri.crim.ca/twitcher/ows/proxy/malleefowl/wps",
			"identifier": "thredds_urls",
			"inputs": {
				"url": "https://colibri.crim.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/ouranos/subdaily/aet/pcp/catalog.xml"
			},
			"progress_range": [
				0,
				10
			]
		}
	],
	"parallel_groups": [
		{
			"name": "FlyGroup",
			"map": {
				"task": "ParsingCatalog",
				"output": "output",
				"as_reference": false
			},
			"reduce": {
				"task": "Subsetting",
				"output": "output",
				"as_reference": true
			},
			"max_processes": 4,
			"tasks": [
				{
					"name": "Subsetting",
					"provider": "flyingpigeon",
					"url": "https://colibri.crim.ca/twitcher/ows/proxy/flyingpigeon/wps",
					"identifier": "subset_WFS",
					"inputs": {
						"typename": "opengeo:NE_State_and_Province_Boundaries",
						"featureids": "NE_State_and_Province_Boundaries.564",
						"mosaic": "False"
					},
					"linked_inputs": {
						"resource": {
							"task": "FlyGroup"
						}
					},
					"progress_range": [
						10,
						100
					]
				}
			]
		}
	]
}
```

> LDP: la limite par défaut semble être 1 GB (SI) (edited)
```
def opendap_or_download(resource, auth_tkt_cookie={}, output_path=None,
                        max_nbytes=1000000000)
```

> LDP: uhmm...
```
for one_resource in request.inputs['resource']:
        # Download if not opendap
        # Adding a maximum file size from a server config file would
        # be possible here...
```

> DB: sur colibri il y a une nouvelle version de malleefowl qui permet d'obtenir un lien opendap remplace thredds_urls par thredds_opendap_urls
pas encore déployé ailleurs toutefois

> RHL: Une erreur même avec le changement https://colibri.crim.ca/wpsoutputs/flyingpigeon/2cbc6166-592f-11e8-832e-0242ac12000b.xml

**Comment by ldperron** [comment]
https://github.com/Ouranosinc/flyingpigeon/commit/365c60c6667d37191351d4a0889b95e778215f08
