### ISSUE TITLE
JupyterLab instance (3)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#58]
Install and configure JupyterLab to work with PAVICS user accounts and get access to stored data.

- General info: https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906
- Installation instructions: http://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html
- Security: https://jupyter-notebook.readthedocs.io/en/stable/security.html
- Docker container: https://github.com/mikebirdgeneau/jupyterlab-docker

Authentication wish-list:

- JupyterLab and PAVICS share the same credential system, so that logging in one allows user to switch to other without reentering credentials.
- Access to JupyterLab is granted to users through Magpie interface (as another service).

Also install list of packages related to hydrology, and make sure relevant streamflow data is available.

**Comment by huard** [comment]
In discussion with Syzygy about this. Hold on work for the moment, we might be able to run it directly on CC.

**Comment by huard** [comment]
Syzygy offered to host a JupyterLab instance for ETS. Following up with ETS.

**Comment by moulab88** [comment]
Ok, on va avancer avec le plan initial.

De : David Huard <notifications@github.com>
Envoyé : 16 octobre 2018 13:27
À : Ouranosinc/pavics-sdi <pavics-sdi@noreply.github.com>
Cc : Labassi, Mourad <Labassi.Mourad@ouranos.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Ouranosinc/pavics-sdi] JupyterLab instance (3) (#58)


@moulab88<https://github.com/moulab88> Pas de nouvelles de Syzygy. Je suggère qu'on avance avec le plan de match initial: une instance de JupyterLab sur une machine à Ouranos qui a accès aux ressources de PAVICS.

**Comment by huard** [comment]
Mourad, est-ce que tu vas pouvoir installer https://github.com/bird-house/birdy dans l'environnement python disponible sur JupyterLab ? On va s'en servir pour interfacer avec les WPS sur PAVICS.

**Comment by moulab88** [comment]
Ok, je vais voir comment je peux l'installer.

**Comment by moulab88** [comment]
Birdy est maintenant installé sur:
https://medus.ouranos.ca:9443/hub/login
et 
https://jphub.ouranos.ca/hub/login  /* The Littlest JupyterHub */
Notebook: Python 3.6 (Birdy)

**Comment by tomLandry** [comment]
@huard next steps here? fully in scope of PAVICS-Hydro too, right?

**Comment by huard** [comment]
Next step would be to go from a jupyterhub to a jupyterlab installation that uses the same credentials as the main PAVICS platform.

**Comment by huard** [comment]
@tomLandry CRIM's mandate here would be to support the JupyterLab service in Magpie and hide it behind the twitcher proxy (to be validated by CRIM to make sure that makes sense).

**Comment by tomLandry** [comment]
@dbyrns C'est du travail à la fois utile (et facturable) sur PAVICS-Hydro et OGC-DOE dépendamment de où on part. Dans les deux cas, on veut livrer d'ici avril. David Caron serait bien placé pour réaliser une bonne partie des travaux.

**Comment by dbyrns** [comment]
Our latest version of Magpie is able to protect arbitrary endpoint without any particular protocol. So you can configure it to protect the endpoint hostname:port/path/to/jupiter/lab and give permission to it or not.
Is it enough for what you have in mind?

**Comment by dbyrns** [comment]
You can look at https://colibri.crim.ca/magpie/ui/services/access for example

**Comment by huard** [comment]
I think so. Great !
Link doesn't work for me.

**Comment by dbyrns** [comment]
David, you will need to log into magpie prior to access that section.

**Comment by dbyrns** [comment]
I talked to @fmigneault and the required feature has been introduce in version 0.6.1
Starting from master we would need to apply the following diff : 
git diff master..786d7d9b22516eb7b3bf8ab387360de0a462887b (only twitcher/magpie related stuff).
The develop version of magpie (0.7.3) has breaking changes that would require update in the frontend but if this feature is required I would take the chance to test the 0.6.1 version.
Until the end of march it would be hard for us to help on that topic so you're welcome if you want to take the lead on that.

**Comment by huard** [comment]
Thanks! Ok, we first need to install a working JupyterLab instance on our end.

**Comment by tlvu** [comment]
@huard, @dbyrns: to close this issue, especially the part about the authentication wish-list:
* JupyterLab and PAVICS share the same credential system, so that logging in one allows user to switch to other without reentering credentials.
* Access to JupyterLab is granted to users through Magpie interface (as another service).

Are we aiming to deploy the current state of PAVICS of master branch (magpie 0.4.5) or develop branch (magpie 0.7.3)?  Note a lot of other pieces are also different between master and develop branch.

Consider full PAVICS stack testing effort if we use the develop branch and/or magpie backport effort if use the much older master branch.

**Comment by huard** [comment]
Ideally we would keep track of the upstream development at CRIM. We did not have the resources to do it so far, but we do now. Better spend time catching up than backporting.

**Comment by dbyrns** [comment]
Latest work has never been consolidated, so we expect some components incompatibility in their latest version. We should fix our priorities soon for the DACCS project and hopefully merge back all the pending branches to a working set. The fact that you have the resources on your side too is even better.

**Comment by tlvu** [comment]
Given the blocking issues with Magpie that prevent shared authentication between Magpie and JupiterHub, we will go forward with deploying JupyterHub on PAVICS but without authentication with Magpie.

**Comment by tlvu** [comment]
An instance of JupyterHub has been added to PAVICS.  It has only 1 `public` user.  Authentication integration with Magpie will be done at a later time once the blocking issues with Magpie can be resolved.  No other components of PAVICS has been updated since JupyterHub so not need any changes in them.

All the jupyter notebooks in this pavics-sdi repo (docs/source/notebooks) can be run.

Closing this issue.
