### ISSUE TITLE
Configure scheduling to account for user-defined external resources (16)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#59]
In the context of ComputeCanada resources being available on top of in-house resources.

To restrict complexity, I suggest this feature to be implemented only for the workflow manager, with no user interface.

**Comment by tomLandry** [comment]
I suggest splitting the load balancing capability from the sceduling into two tasks. Different beasts for different use cases.

**Comment by tomLandry** [comment]
Put in light of these findings:
https://github.com/Ouranosinc/raven/issues/36
