### ISSUE TITLE
Add hummingbird to PAVICS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#6]
Reasonable ? It provides some CDO tools and a remapping process that is in our list of deliverables to CANARIE. Other option is to add a regridding process in FP. 
Please advise.

**Comment by tlogan2000** [comment]
I would say it might be worth it.  Are there conversion tools included? 
Converting grib2 to netcdf in CDO is by far the easiest way that I have found.     
Could make mass import of CANSIPS / other data for ECCC datamart into PAVICS much easier in any future 'operational' applications.  E.g. monthly updates of seasonal forecast from RPN ....
Download, conversion, import could all be integrated into the workflow.

**Comment by bstdenis** [comment]
Added the docker automated build to dockerhub: https://hub.docker.com/r/pavics/hummingbird/builds/
Will add to the docker-compose shortly.

**Comment by huard** [comment]
I'd like to know (eventually) how you do this. Trevor, are you familiar enough with the process to document it ?

**Comment by Zeitsperre** [comment]
Not yet, no. I'll add this to my list of things to learn. I'll speak with @bstdenis to know more.

**Comment by bstdenis** [comment]
Hummingbird now integrated in our docker-compose and magpie in https://github.com/Ouranosinc/PAVICS

The hummingbird docker image works locally as far as the GetCapabilities is concerned. Testing an actual process on the deployed platform remains to be done.

**Comment by bstdenis** [comment]
Now deployed on boreas. Anyone has a use case they want to test?

**Comment by huard** [comment]
identfier=ensembles&DataInputs=dataset=<a small test
ensemble>&operator=ensmean

**Comment by huard** [comment]
Clicking on a process, no form to enter inputs is presented, and there is no Execute button.

**Comment by huard** [comment]
Mourad, est-ce que c'est possible que Hummingbird ne soit pas enregistré sur Phoenix dans Magpie ? Je pense que l'UI utilise phoenix pour inspecter les processus.

**Comment by moulab88** [comment]
Effectivement, tu n’avais pas les droits d'utiliser Hummingbird, maintenant tu les as, peux-tu réessayer

**Comment by huard** [comment]
Toujours le même problème d'interface qui ne présente pas le formulaire d'input. Ça prend je pense les permissions pour describeProcess.

**Comment by huard** [comment]
Hummingbird fonctionne bien quand on appel directement ses services. Par contre, Phoenix retourne le message "no applicable code" quand on veut examiner les processus individuels.

**Comment by huard** [comment]
@dbyrns On va avoir besoin d'aide là-dessus. On a ajouté hummingbird à notre installation, mais il doit manquer une étape de configuration parce que ça marche juste à moitié.

**Comment by tomLandry** [comment]
David B. est bien la bonne personne à tagger, mais progressivement Francis prendra un rôle de support première ligne plus important. Just so you know. En passant, à l'interne on a gardé tous nos codes de temps ouverts pour assurer la continuité de PAVICS en attendant une planification actualisée.

**Comment by huard** [comment]
C'est noté. Est-ce que je commence tout de suite à tagger Francis ?

**Comment by tomLandry** [comment]
Je laisserai à David B. le soin de déterminer quand et dans quelle mesure (ou pour quelles composantes) il souhaite un support de Francis. Sinon, si tu vois que c'est du code ou des commentaires où Francis est déjà intervenu, je ne vois pas de mal à attirer son attention.

**Comment by huard** [comment]
Excellent.

**Comment by dbyrns** [comment]
Can we close this issue now that Hummingbird is included to PAVICS?
Looks like the only remaining issue is covered by https://github.com/Ouranosinc/PAVICS-frontend/issues/61

**Comment by huard** [comment]
I'd close the other instance, I don't think it's a frontend problem, more a configuration or permission problem.
