### ISSUE TITLE
Allow users to select the hardware a process will run on (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#60]
Original: Create user interface allowing user to set-up preferences for where a process will be run (in-house or computecanada). 
Updated: Modify Birdy to support multiple servers and select the one with the fastest response time by default. Let user specify preference.

**Comment by tomLandry** [comment]
In the OGC testbeds, that would be the equivalent of Twitcher deploying to a specific "ADES" - Application Deployment and Execution Service. We have that at experimental level, so probably demonstrable to CANARIE. Operationalization could only be done in PAVICS-Hydro second phase though.

**Comment by huard** [comment]
Good enough.

**Comment by tomLandry** [comment]
@dbyrns Looking at the slim description and issue title here, do your feel the same? It's the same EMS - ADES concept. Of course, deployment to Calcul Canada would have to be done in the upcoming year, in the project's maintenance phase. As @lalondma told us, CC are a bit behind the curve anyway.

**Comment by dbyrns** [comment]
Well an EMS selecting an ADES to move the processing where the data is located is not really the same as allowing a user to choose where he want to execute a process (based on speed/cost ratio I guess) and on different type of architecture i.e we cannot presume that CC and PAVICS will ever have the same interface (as for ADESes).

**Comment by dbyrns** [comment]
Indeed the concept is the same, but I highly doubt that the implementation will help us here.

**Comment by dbyrns** [comment]
That was my understanding and it's completely unrelated to the OGC work. 
Here are the challenges I foresee :  
1. How the aggregator can determine that 2 providers do the same job (currently we cannot register 2 providers having the same name in magpie), maybe by using the GetCapabilities Title?
2. Choosing the right server is not trivial... load, proximity, etc. these are not available right away and are not part of any standard.
3. And then we have to rewrite the UI to allow this type of interaction

**Comment by dbyrns** [comment]
1. serveur.identifier is not a WPS thing? But yes the collection of process ids can be considered as a unique identifier, just not very practical.
2. running processes are meaningless unless you know the hardware available threads, but interesting metrics. Just how to get them? Customizing PyWPS with special route to obtain a "good choice" rating? And handle cases where that route doesn't exist...
3. Does birdy offer the aggregation of multiple servers or is it a single server wrapper? Could be a good candidate to package 1. and sort the better server using 2.

**Comment by huard** [comment]
1. Sorry, its ServiceIdentification/Title or ProviderName in the getCapabilities XML. 
2. What if we time the `describeProcess` requests and use that to rank servers ? Birdy could launch that in the background every 2-3 minutes and adjust the ranking. 
3. Not yet, it is for the moment a single server wrapper, but adding support for multiple servers would be relatively easy (about a day of work).

**Comment by dbyrns** [comment]
We are working on a new bird based on the EMS (Execution Management Service) developed in OGC's Testbed14. The main features was a REST interface, dynamic docker application deployment, CWL workflows, monitoring and results retrieval. As an extension of the testbed we are now trying to encapsulate existing WPS 1.0 (and ESGF CWT API) provider processes as EMS applications. This will allow us to offer them as processes in a single list (processes of the EMS) [Point 1]. Birdy could be updated to support also the new REST interface following the next gen OGC WPS-T 2.0 standard [Point 3]. And PAVICS will use it as soon as we can work on it [Also point 3]. As a nice to have, the EMS could implement a logic to determine the best suited process provider when running a job [Point 2].

So as you can see we now have a funded project to make that happens!

**Comment by tomLandry** [comment]
This issue is currently assigned to @lalondma because he has been working on launching Docker containers on ComputeCanada. If we need to take a step back in Architecture before going forward, that's fine but we need to show something in April.

**Comment by dbyrns** [comment]
The discussion has indeed run over this issue topic. Offering Calcul Canada as typical WPS is still the main issue. The EMS will help the client to choose transparently between the Cloud version of PAVICS and CC only if CC can be exposed in the same manner.
