### ISSUE TITLE
Connect ComputeCanada accounts to PAVICS (16)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#61]
Let user assign a CC identity to its PAVICS account. 

We need to be able to launch a service on CC and access the output. 

- Can we access files that are stored on CC ? 
- Can we transfer files between the user workspace to the user's CC directory ?

Related: #59, #60, #62, #63

**Comment by tomLandry** [comment]
Yellow flag for everything account or security-related. This is work conducted partly at OGC in the "federated infrastructures" aspects and to be delivered by CRIM and others. A connection to Canadian Access Federation (CAF) of CANARIE is on the short-term roadmap.

**Comment by huard** [comment]
This is not a blocker, but I'd like to have a clear roadmap to get there. 
Alternatively, if If there are serious show-stoppers to deliver this for July, what is the potential of substituting the CC target for a public/private cloud.

**Comment by tomLandry** [comment]
With the information I have at hand right now, I still think we should get advice from CANARIE before/while approaching Compute Canada. Several reasons, I see here that Compute Canada are in the process of joining or interoperability with CAF: https://www.canarie.ca/wp-content/uploads/TAD-computecanada.pdf

Second, there is a strong requirement from European Space Agency and NRCan in OGC testbed to support AuthN from EduGain (SAML technology). In Europe, it's driven by GEANT, in Canada by CANARIE. It's getting materialized in PAVICS through new support of WSO2 proxy in Magpie. This type of proxy should in theory bridge several types of Auth. @huard I have some tech material on this, but currently restricted to OGC members. Sending this to @lalondma that can also consult with colleague Caroline Musy that made quite a few tests on this.

**Comment by tomLandry** [comment]
Link to recent OAuth2 tests conducted for OGC testbeds with a WSO2 proxy (restricted link): https://www.crim.ca/confluence/display/OGC/Exploration+OAuth+2

**Comment by fmigneault** [comment]
@tomLandry 
Magpie support of WSO2 is somewhat complete, only need to deploy new versions and run some tests to see if anything is missing. If CC is registered directly under WSO2, it should be supported by Magpie natively, but if instead OAuth2 validation has to be completed directly with CC as a IdP, I will need their auth URL to integrate them to Magpie as an additional external login provider.

**Comment by tomLandry** [comment]
@fmigneault : don't take any additional action for now, just wanted you to be aware of this. I'm looking to see if the indirect route (WSO2 -> CAF) is practical, but that's to be coherent with OGC/ESA/CANARIE/NRcan roadmap. We will know soon if it's better to go to the shortcut of OAuth2 to CC.
