### ISSUE TITLE
Advanced spatial regridding

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#66]
# WP 4.2
- [x] Evaluate whether ESMF meets the internal needs of Ouranos.
- [x] Confirm ESMF regridding works out of the box with rotated pole grid. 
- [x] Provide ESMF regridding tools on a performance optimized architecture. 
- [ ] Develop wizard to help users select the *right* interpolation method for a given usage, objective, variable.

**Comment by huard** [comment]
@cothel Pourrais-tu donner ton opinion à savoir si les outils de regridding de ESMF répondent aux besoins internes ? 

https://www.earthsystemcog.org/projects/esmpy/

**Comment by cothel** [comment]
Je crois que c'est très pertinent. Permet l'usage de masques lors de l'interpolation. Nos options préférées genre "with respect to ground cover" seront donc possibles. Merci de vérifier que ces outils fonctionnent bien avec la grille régionale "rotated pole" de MRCC5 (j'ai l'impression que c'est le cas)

**Comment by huard** [comment]
https://esgf.github.io/esgf-swt/data/2016/04/01/how-rotate.html

**Comment by cothel** [comment]
Tant mieux! 
Le fait que l'opération nécessite 3 commandes montre qu'il est peut être avantageux de faire un maximum de calculs sur la grille native et de faire le regridding sur le résultat. Ça limite aussi les artefacts des interpolations.

**Comment by cothel** [comment]
Mes préoccupations n'ont pas changé par rapport aux messages de 2019. La provision de pouvoir interpoler "with respect to" (masque, ground cover, etc) est extrêmement importante. Perdre cette option serait un recul majeur en SAC.
