### ISSUE TITLE
Hydroclimatic indices

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#67]
# WP 4.3

- [ ] Either wrap climdex.pcic into WPS or implement them using xarray/dask/ocgis. 
- [ ] Support non-gregorian calendars
- [ ] Support missing data handling and thresholds (e.g. criteria to accept or reject index computation depending on missing data fraction)
- [ ] indices for streamflow time series
- [ ] sea ice indices

## References
http://etccdi.pacificclimate.org/list_27_indices.shtml

**Comment by Balinus** [comment]
I guess it's not in the original deliverable but how about something related to GEV theory? Might be useful.

**Comment by huard** [comment]
Frequency analysis is in the ETS project, so yes.

**Comment by huard** [comment]
Mostly done. Issues about this should be opened in Raven.
