### ISSUE TITLE
Copy geographic layers from outarde geoserver to boreas geoserver

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#7]
See layers available in https://outarde.crim.ca/

**Comment by Zeitsperre** [comment]
Outarde geoserver keeps timing out for me. Is http://outarde.crim.ca:8087/geoserver the proper address:port?

**Comment by dbyrns** [comment]
No. The only port available outside of the CRIM is 443. Geoserver is available on the /geoserver route.
https://outarde.crim.ca/geoserver

**Comment by Zeitsperre** [comment]
Shapefiles are up. Styles don't seem to transfer over that well using QGIS GeoServer Explorer plugin. Will be adjusting line width and transparencies tomorrow.

**Comment by huard** [comment]
Nice !
And please check the layer names so they are consistent and clearly understandable (mrc_poly, region_admin_poly).

**Comment by huard** [comment]
Complété ?

**Comment by Zeitsperre** [comment]
Almost. I'll see what's going on with some of the styles. For some reason, they aren't saving properly. Might be able to finish this today.

**Comment by Zeitsperre** [comment]
New styles are up and layer names are now consistent.
