### ISSUE TITLE
Add CMIP6 sample in testdata

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#76]
Add small (1Mb) sample file using the CMIP6 conventions to THREDDS testdata directory.

**Comment by Zeitsperre** [comment]
I've put in a request to register for CMIP6 data access. I`m not sure if there's much else I can do. Do you happen to know if anyone at Ouranos has established access to any CMIP6 data we can play with in the meantime?

**Comment by Zeitsperre** [comment]
I now have early access to the newer CMIP6 data. I`m adding an IPSL 1%-CO2 precip model output (3GB) to the CRIM testing servers. DataCatalog will need to be run afterwards. @ldperron, I'll keep you posted.

**Comment by ldperron** [comment]
I ran it everywhere, except for colibri... something seems currently broken in there.

**Comment by ldperron** [comment]
Crawler finally got started on Colibri.
