### ISSUE TITLE
Convert PAVICS code base to Python3

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#77]
[Time is running out.](https://pythonclock.org/)

There is roughly 1.5 years of Python2 relevance before much of the code base is rendered "unsupported". Many of the more popular libraries behind PAVICS should be available for Python2+3 at this point. Python3 also boasts many improvements when it comes to processing speed and memory management that PAVICS could benefit from.

There are several methods and examples available showcasing how other large projects have managed the 2->3 migration (e.g. [Jason Fried's presentation at PyCon 2018](https://www.youtube.com/watch?v=H4SS9yVWJYA)). Tools such as `six` can determine the code sections that work in both Python2 and Python3 and `2to3` can perform much of the smaller changes (e.g, `print stuff` --> `print(stuff)`).

It may be worthwhile to start integrating build checks for Python3 even if they will absolute fail in the immediate future. Thoughts?

**Comment by huard** [comment]
Have you identified specific issues with py3 compatibility ?
The birdhouse build process runs tests for py2 and py3 at each push, so I'm not really worried. Prove me wrong.

**Comment by Zeitsperre** [comment]
From what I've seen, the most significant change would come in updating the build recipes for key libraries that are built in Conda to Python3. Good to know that birdhouse has got this covered. If this is simply a matter of specifying Python3 within the build recipes for our components or If the conversion process is simply a matter of removing `import future` statements, it seems like we're already there.

Seeing as I'm not a developer, the only major issues I can see arising from the conversion would be API calls for some important libraries may have changed. Pinning libraries to specific versions may help but I don't know how one goes about ensuring that libraries continue to "play nicely with each other". Again, I'm not the expert here. Not trying to "stir the pot" here, just wondering if there's a mid/long-term plan for support.

**Comment by huard** [comment]
Got it. I know there are a couple of py3 issues with upstream packages, but I don't believe any of them is a show-stopper. An action point could be to check that our tests runs on both 2 and 3 systematically for all packages. More generally, moving stuff from Ouranosinc to birdhouse would also be a good idea.

**Comment by huard** [comment]
Any remaining issues to be addressed ?

**Comment by Zeitsperre** [comment]
I think the only major issues that we've run into might be in the cookiecutter template we use. The difference between Miniconda2 and Miniconda3 is the base python version launched on install. Once those have been tracked down in the various projects and updated, I think we would be good to close this.

**Comment by huard** [comment]
@Zeitsperre Status ? The cookie-cutter does not install Miniconda anymore.

**Comment by Zeitsperre** [comment]
I think we're about good to close this. If there are any artefacts left in a few birds/services, I imagine they will be modernized when found.
