### ISSUE TITLE
Add CLIMEX subset to PAVICS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#8]
Add enough ensemble member to showcase distributed parallel task scheduling.

**Comment by huard** [comment]
- 5 premiers membres (kda à kde)
- Domaine : Québec méridional élargi (43°N à 53.5°N et 82°O à 57°O)
- Variables et résolution temporelle: précipitations et températures journalières, précipitations horaires.

 Les données journalières seront post-traitées par Marco Braun. 
Je suggère de mettre à la fois les données originales et les données post-traitées.

**Comment by huard** [comment]
Mise-à-jour du statut de la demande demandée par Simon Ricard.

**Comment by bstdenis** [comment]
Les données sont copiées sur boreas, j'ai également ajouté à la documentation (data_management) des infos pour faire un crawling partiel, puisque c'est rendu beaucoup trop lourd de crawler le thredds au complet à chaque fois. Prêt à être crawler dès que PAVICS-DataCatalog est mis à jour sur boreas.

**Comment by bstdenis** [comment]
Internal script used to properly copy the data to boreas is here: https://github.com/Ouranosinc/scripts-internes
