### ISSUE TITLE
ICCLIM flyingpigeon errors

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#81]
Unable to run ICCLIM_ indices from Boreas
following code gives the error:
owslib.wps.WPSException : {'locator': None, 'code': 'NoApplicableCode', 'text': 'Process error: wps_ocgis_func.py._handler Line 161 Failed to read input parameter [Errno 2] No such file or directory'}

url to netcdf file was copied directly form the THREDDS web UI
(Tried both openDAP and regular url just to be sure)

CODE:

`from owslib.wps import WebProcessingService, monitorExecution, printInputOutput
import requests`

`def main():`
`    listMod = [
        "https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/fileServer/birdhouse/ouranos/cb-oura-1.0/ACCESS1-3/rcp45/day/tasmax/tasmax_day_ACCESS1-3_rcp45_r1i1p1_na10kgrid_qm-moving-50bins-detrend_1950.nc",
         ]`

`    wps_url = 'https://boreas.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps'`
`    wps = WebProcessingService(url=wps_url, verbose=False, skip_caps=False)`

    for process in wps.processes:
        print '%s \t : %s ' % (process.identifier, process.abstract)

    # try ICCLIM indices
    proc_id = 'icclim_TX'
    proc = wps.describeprocess(proc_id)
    print( '')
    for i in proc.dataInputs:
        print  '%s \t : %s ' % (i.identifier, i.abstract)

    myinputs = [('resource', listMod[0]), # Change opendap to normal url
                ('grouping', 'yr') # grouping yearly average
                ]
    execute = wps.execute(
        identifier=proc_id,
        inputs=myinputs,
    )

`if __name__ == '__main__':`
`    main()`

**Comment by huard** [comment]
Ça marche, donc ?

**Comment by tlogan2000** [comment]
Oui ça marche

**Comment by tomLandry** [comment]
Update? Is it deprecated by XClim capabilities? Can we track that in CCDP?

**Comment by huard** [comment]
Efforts should focus on Finch. So yes, deprecated.
