### ISSUE TITLE
Add Colour-blind accommodating Colour Ramps

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#82]
Low priority for now, but for visualizing multi-modal distributed data, it would be good to add a color ramp option that accommodates users with colour-blindness.

![image](https://user-images.githubusercontent.com/10819524/44216405-da77d500-a142-11e8-8146-1d63f7067f58.png)

Justification for adding this feature can be found here: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239 (The authors have some examples of the "Cividis" ramp available at https://github.com/pnnl/cmaputil)

If we want to simply work with the more established Color-Brewer library, a good alternative is their "PuOr" ramp.

**Comment by huard** [comment]
Front-end is not in development anymore.
