### ISSUE TITLE
Define simple example of service using data from CMC

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#83]
Get opendap or file link from CMC catalogue
Process data

**Comment by huard** [comment]
The original idea was to take seasonal predictions and compute relevant indicators, such as the likelihood of heatwaves, snowfall accumulation, etc. 

If we were to do this, the steps would look something like this:
- Select the indicator of interest (e.g. heatwaves)
- Identify the WebCoverageService layers for the relevant variables (daily min/max temperatures for seasonal predictions)
- Make a request for the layers over the entire forecast
- Convert the data into an xarray.DataArray
- Compute the xclim indicator on the DataArray
- Create graphics synthesizing the results

For reference, this is how we access GeoMET WCS server. 
```
from owslib.wcs import WebCoverageService
geomet_wcs_url = 'http://geo.weather.gc.ca/geomet/?lang=en&service=WCS'
wcs = WebCoverageService(geomet_wcs_url, version='1.0.0')
layer_ids = ['RDPS.ETA_PR',] # 'REPS.DIAG.3_PRMM.ERMEAN'
lid = layer_ids[0]
meta = wcs.contents[lid]
meta.title
out = wcs.getCoverage(identifier=layer_ids, bbox=meta.boundingBoxWGS84, crs='EPSG:4326')
```

**Comment by tomLandry** [comment]
Excellent. For your information, I'm meeting with Tom Kralidis in the next few minutes here at CRIM. Points of discussion should include access to CANSIPS and daily climate observation (station data). @tlogan2000 should know about this from our action points from the Data WG. These are seen like valuable but not trivial for several reasons (that I will not cover here). My understanding is that your example below could be rewritten with CANSIPS data, but I'm not sure.

**Comment by huard** [comment]
I don't see CANSIPS in the WCS content from geomet. I mean, even better for us would be to have direct OPeNDAP access to CANSIPS data.

**Comment by tlogan2000** [comment]
I would mention that inclusion of CanSIPS for the intial launch of the CCCS portal would not include any derived indices calculation, as we unlikely have time to validate any new products.  Short term we would ideally directly connect to ECCC's 'summary' CanSIPS products (predicted temperature anomalies, or probabilities of the next month being warmer / colder than average) leaving the data control/quality in the hands of CMC who are more knowlegeable than we are for the moment.  FYI Marko Markovich is our contact for CanSIPS in terms of which data/info they are confortable with (potentially) providing for the portal...  Longer term it would absolutely be of interest to work with CMC on the calculation of indices

**Comment by tlogan2000** [comment]
I don't think that CanSIPS is on GeoMet.  Right now there is only access to the raw output via the DataMart.  However they have some data treatment chain to produce the summary info every month... if that output could be integrated into GeoMet that would be great for the needs of the portal.

**Comment by tomLandry** [comment]
Ok, will report in more details elsewhere. But for my understanding @tlogan2000 is right, CANSIPS on DataMart right now. OPEnDAP support at ECCC (through PyDAP, not THREDDS) is upcoming in a few months and it will be tight but _possible_ for launch. Short-term, having a copy at Ouranos and exposing it on THREDDS would make sense - but idea it would be temporary.

**Comment by huard** [comment]
@tomLandry Milestone?

@tlogan2000 We can add cansips files to our tests for xclim. Once we have a working finch server for xclim, we can create a custom WPS process to run these indices on cansips data.

**Comment by tomLandry** [comment]
Well David, this issue is labelled "Define simple example of service using data from CMC", so I consider it solely a requirement gathering task. As such, I deem it urgent for the collaborative portal to have our "CMC user story" ready for our mutual understanding. We can probably concentrate on CANSIPS here and defer station observation requirements elsewhere.

As for the milestone of having that user story delivered, it's another matter. I cannot answer right away as this would get "groomed", prioritized and done with our Agile process (to be re-communicated soon).

**Comment by tomLandry** [comment]
@jslandrycanada Welcome to PAVICS general backlog! The idea is to cross-reference issues we have here into a backlog specific to the climate data portal, to be created. Note that the data portal backlog will link to other projects of interest (such as https://github.com/ECCC-CCCS) as well as containing issues only pertaining to that particular project. A backlog is a master list, a bag where everything relevant is stored. t the start of each iteration (each month), we should go through it and label priorities, blockers and work we can tackle in the period. Then participants have to report on this particular subset of issues at the end of the period.

**Comment by tomLandry** [comment]
Can we have an update on this? Could we process this issue in CCDP?

**Comment by huard** [comment]
Please clarify your request. 
Seems reasonable.

**Comment by tomLandry** [comment]
Ultimately, I'm questioning if this issue is still required or relevant. De facto, we have a CMC use case or something close to it in CCDP - or we will have one at the end of the project. Asking if we can close the issue here, but I don't want us to lose ideas and information.

**Comment by huard** [comment]
I'd like to see a notebook in our docs exercising access to CMC data and a simple analysis.

**Comment by tomLandry** [comment]
Then I consider adding notebooks in CCDP as a way to show functionnalities, and deliver API-based features instead of Portal/Platform elements. What do you think?

**Comment by huard** [comment]
Ok for the Ouranos point of view, but I don't know about CCSC expectations regarding this.

**Comment by huard** [comment]
Done in Raven, now using GEPS forecasts from the DataMart. Bypassing GeoMet for now due to missing metadata in netCDF output.

**Comment by jslandrycanada** [comment]
Salut David,

Je ne suis probablement pas la bonne personne...

JSL
