### ISSUE TITLE
CANARIE Compliance

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#84]
### PAVICS Platform
 - [x] The "Try Me" link just points to a TODO page. **points to pavics.ouranos.ca**
 - [x] I don't see any mention of CANARIE's funding on the linked pages.

### Bias Correction Service
- [x] Documentation links to a API endpoint's documentation that does not appear related to Bias correction (https://ouranosinc.github.io/pavics-sdi/processes/basic_climate.html#spatial-regridding),
- [x] Release notes link to PAVICS-SDI
- [x] Source links to flying pigeon https://github.com/Ouranosinc/flyingpigeon.
- [x] Try me links to TODO.

### Climate Indices Service
- [x] Release notes link to PAVICS-SDI.
- [x] Source links to flying pigeon https://github.com/Ouranosinc/flyingpigeon.
- [x] Try me links to TODO.

 ### High resolution spatial gridded data renderer
- [x] Documentation is just 'other projects'.
- [x] Release notes is PAVICS-SDI.
- [x] Source is ncwms2 Web Map Service https://hub.docker.com/r/pavics/ncwms2/ (I don't see no details as to what this is in relation to the service name). **The documentation should explain the link.** 
- [x] "Try me" links to TODO.

### Node
- [x] Documentation is generic.
- [x] Release notes link to PAVICS-SDI.
- [ ] Source is PAVICS-SDI **Not clear what source should be, as the service is a collection of servers**. _I feel as though this requires feedback from the CANARIE people as this service wrt ESGF is not enabled at this time._
- [x] "Try me" links to TODO.

### Spatial and temporal data slicer
- [x] Documentation is to 'Spatial and temporal subsetting' is this the same?  **Yes**
- [x] Release notes is PAVICS-SDI.
- [x] Source code is flying pigeon. **Now points to subsetting process within FlyingPigeon**
- [x] "Try me" links to TODO.

**Comment by huard** [comment]
If we take the tutorials from last week's workshop and include them in the docs, I think we could solve some of these try-me.

**Comment by tomLandry** [comment]
Oh absolutely, for trying services JupyterLab is a perfect setup.

**Comment by Balinus** [comment]
Note that Jupyter Lab is really close to a 1.0 release.

**Comment by huard** [comment]
I think for now just a code example would do.

**Comment by dbyrns** [comment]
As I see this, this issue is related to the content and not the technical part of the api service. So I will let you handle that unless you need help on a specific issue. As a reminder, all the links can be modified here : https://github.com/Ouranosinc/PAVICS/blob/master/birdhouse/config/canarie-api/docker_configuration.py.template

**Comment by huard** [comment]
Thanks! I pinged you exactly to get that info.


Le mer. 26 sept. 2018 06:38, David Byrns <notifications@github.com> a
écrit :

**Comment by huard** [comment]
@Zeitsperre Solving some of these issues will require making an official release of services that are at the moment only in our pavics branch. I think this requires merging our stuff upstream.

**Comment by huard** [comment]
@Zeitsperre could you take care of the try-me ? If you could take some of the relevant tutorials for the workshop and add them to the pavics-doc, that would be great. Please use the fix_84 branch on PAVICS to update the canarie-api links (see David's comment above).

**Comment by tomLandry** [comment]
@huard as time goes by, "node" is getting pretty close to Twitcher in the OGC testbed. It's more of a proxy, but that is the endpoint that links to infrastructures that we were considering.

**Comment by huard** [comment]
Thanks, is there documentation and try-me examples that you can point me to ?
