### ISSUE TITLE
Twitcher proxy fails at proxying geoserver routes

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/pavics-sdi#88]
PUT https://hirondelle.crim.ca/twitcher/ows/proxy/geoserver-api/workspaces/User_Custom_Regions/datastores/User_Custom_Regions/file.shp
returns:
```{"type": "application/json", "code": 500, "call": {"content": "None", "exception": "<HTTPBadRequest at 0x7f3abfad3640 400 Bad Request>"}, "detail": "Failed to find requested service type."}```

When using a valid token; user cypress, part of group user which have following permissions:
![image](https://user-images.githubusercontent.com/14914217/47529664-6a8a7700-d876-11e8-8f33-adf4cfed3f29.png)

Calling PUT https://hirondelle.crim.ca/geoserver/rest//workspaces/User_Custom_Regions/datastores/User_Custom_Regions/file.shp with the same binary file returns 201 as expected

**Comment by fmigneault** [comment]
Should be resolved via Ouranosinc/twitcher#33
Deployed on colibri & hirondelle.
@Renaud009 Let me know if it's working.
