### ISSUE TITLE
Connect to THREDDS server from console

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#90]
We have one user who wants to access directly the THREDDS server data. 

Can we login from a python console to the THREDDS server ? 
How do we pass credentials ? 

This needs to be added to the documentation.

**Comment by huard** [comment]
@davidcaron Sans faire le travail, peux-tu me pointer dans la bonne direction ?

**Comment by dbyrns** [comment]
The solution of @davidcaron is good and could be added to a documentation for power user. No other protection has been added to THREDDS so as long as you target the twitcher proxy with the proper cookie everything will be fine.

**Comment by huard** [comment]
Ok, will add to the docs and close the issue.
