### ISSUE TITLE
ServiceException: Maximum number of parallel running processes reached. Please try later.

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#92]
FlyingPigeon on PAVICS intermittently throws this error. At other times, I get a Bad Gateway error. 

@dbyrns Could it be due to the postgres DB ? Is there a clean-up of the DB to do ?

**Comment by dbyrns** [comment]
PyWPS is not good at recovering from crashed processes. So when a process crashes  the running process count is not reduced and thus eventually the max running process count is reach even without anything in progress.
A restart resolves that issue. Sadly the best solution to this is making sure that our processes errors can be handled properly. The issue arised for me much more often while debugging and killing processes manually.

**Comment by moulab88** [comment]
We have the same problem after a restart. Maybe flushing wps_requests and wps_stored_requets tables of FlyingPigeon DB resolve the problem?

  flyingpigeon=# SELECT COUNT(*) FROM pywps_stored_requests; 
 count 
-------
     7
(1 row)

flyingpigeon=# SELECT COUNT(*) FROM pywps_requests; 
 count 
-------
 22596
(1 row)

**Comment by huard** [comment]
Ça marche ! Yé !

**Comment by moulab88** [comment]
The BD was flushed. It works for me too.

**Comment by dbyrns** [comment]
@moulab88 in the DB do you have access to the process id related to the job? I'm looking for a way to clean automatically the database... Unless you thing it is an isolated event and the solution was good enough in which case we can close the issue.

**Comment by moulab88** [comment]
Yes I can see the pid in the BD. But I can't see the process in FP we should install "ps".
We can use also the "status" and/or "time_end" fields of the wps_request table, per example: 
DELETE FROM wps_request WHERE time_end < '1-1-2019' 

I think it is an isolated event whith a lot of errors logs. We can keep the solution.

**Comment by dbyrns** [comment]
Ok fine.
