### ISSUE TITLE
Test ESGF CWT API on our Jenkins

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#99]
Add these notebooks to the list of notebooks we hit with Jenkins: 
https://github.com/ESGF/esgf-compute-api/tree/devel/examples

**Comment by tlvu** [comment]
Close when they are not running yet?

**Comment by huard** [comment]
You are right, I went too fast on this one.

**Comment by tlvu** [comment]
WIP branch: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/enable-esgf-notebooks-in-jenkins
Jenkins test build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/enable-esgf-notebooks-in-jenkins/

**Comment by huard** [comment]
Closing. There is a new direction for CWT.
